Make date time picker columns grow when label is too wide
laravel-filament/filament pull request #10008
Opened 2023-12-01 18:23 UTC by ariaieboy

before in fa lang
![image](https://github.com/filamentphp/filament/assets/15873972/94a4bbbe-3241-4cc9-bfae-ddf38743de78)

after in fa lang
![image](https://github.com/filamentphp/filament/assets/15873972/3825ea53-883d-40ff-beaf-4107e0a8be50)

after in en lang
![image](https://github.com/filamentphp/filament/assets/15873972/7806f850-db2c-4d41-a515-e5bf003b43a2)

2023-12-02 21:18 UTC, danharrin commented
Pretty sure there is a reason we did it like that before

2023-12-02 21:45 UTC, zepfietje commented
> Pretty sure there is a reason we did it like that before

Yeah, probably for min width of the date buttons.

2023-12-02 22:22 UTC, danharrin commented
In the min width the `spacing.7` bit?

2023-12-02 23:15 UTC, zepfietje commented
Yeah I suppose.

2023-12-04 14:26 UTC, zepfietje requested changes
Please make it so that the default width is still used, and the buttons only grow when the label is too wide.

2023-12-05 09:59 UTC, danharrin commented on packages/forms/resources/views/components/date-time-picker.blade.php
> +                    <div class="gap-y-3">
Gap only works with grid or flex elements, right?

2023-12-05 10:06 UTC, ariaieboy commented on packages/forms/resources/views/components/date-time-picker.blade.php
> +                    <div class="gap-y-3">
I've only changed line 197 what is this codes 🤔

2023-12-05 10:07 UTC, danharrin commented on packages/forms/resources/views/components/date-time-picker.blade.php
> +                    <div class="gap-y-3">
Please check the full git diff

2023-12-05 11:09 UTC, zepfietje commented
Tested the change and it seems to keep the original behavior when labels aren't too wide.
Thanks, @ariaieboy!

2023-12-05 11:10 UTC, zepfietje approved these changes

2023-12-05 11:11 UTC, merged