Allow individual logout for each of the panels v2
laravel-filament/filament pull request #10408
Opened 2023-12-20 09:16 UTC by soymgomez

## Description

Since version 3.x allows to manage several panels from the same installation, the lines to destroy the user session when logging out do not make sense.

Because when logging out from one of the panels is done automatically from the rest.

This PR is related with #10372 with a logic to detect if the user has more than one logedin panels
- [ ] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

2023-12-20 22:28 UTC, danharrin commented
I can't seem to reproduce a scenario where `login_` items are added to the session, how does this work?

2023-12-21 08:54 UTC, soymgomez commented
> I can't seem to reproduce a scenario where `login_` items are added to the session, how does this work?

It happened to us in a new installation of filament adding a second panel(https://filamentphp.com/docs/3.x/panels/configuration#creating-a-new-panel) and setting a diferent guard. 

With this one you can login in both panels at the same time but logging out in one of them destroys the whole session.

2023-12-22 11:38 UTC, tonypartridge commented
Are you adding a custom session driver / middleware for the login_ session key?

2023-12-23 16:20 UTC, danharrin requested changes
Please can you send a simple reproduction repository that works with this setup, so I can test it?

2023-12-24 17:20 UTC, danharrin commented
Just tested this locally and it doesn't seem to work at all 🤷‍♂️

2023-12-24 17:20 UTC, closed without merging