Add fix-overflowing-images support to Table ImageColumn
laravel-filament/filament pull request #10433
Opened 2023-12-22 00:20 UTC by drbyte

## Description

Extends #10415 "Fix overflowing images" on infolists (from Filament v3.1.25) by (optionally) adding `flex-wrap` to table image column as well.

While not enabled by default, this PR adds the `->wrap(true)` option to enable the wrapping.

When a table is displayed as a normal table, one will probably want to use limit() instead of wrapping, else images will stack vertically. However, when a table is displayed in a grid, using `wrap(true)` will pleasantly display the images, instead of overflowing out of bounds.

Doesn't interfere with existing `stacked`/`overlay`/`limit`/etc features.

**Grid Table:**

Before:
<img width="667" alt="Screen Shot 2023-12-21 at 1 39 37 PM" src="https://github.com/filamentphp/filament/assets/404472/c4b8dddb-244a-4c5c-9e69-406e2bc69931">

After adding `wrap()`:
<img width="604" alt="Screen Shot 2023-12-21 at 1 39 15 PM" src="https://github.com/filamentphp/filament/assets/404472/ea1d636f-f39b-43f1-b6e4-66256cf8818c">

**Normal Table:**
Before:
<img width="1153" alt="Screen Shot 2023-12-21 at 1 54 27 PM" src="https://github.com/filamentphp/filament/assets/404472/eccdd949-9de8-4056-aac4-a971b4512e6d">

After adding `wrap()` (obviously not everyone will want multiple lines, so they can still use `limit()` instead)
<img width="1089" alt="Screen Shot 2023-12-21 at 1 55 10 PM" src="https://github.com/filamentphp/filament/assets/404472/db8ebd5f-c53d-49d8-b131-cd80b56487d3">

Caveat:
If one adds `wrap()` to a normal row-based table, the images will stack:
<img width="248" alt="Screen Shot 2023-12-21 at 3 09 52 PM" src="https://github.com/filamentphp/filament/assets/404472/cfbe06aa-350a-49f2-8aa3-99f2ef6fa332">

- [x] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [x] Make sure code style follows the rest of the codebase.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation updates included

2023-12-23 16:22 UTC, danharrin requested changes
Please extract `wrap()` / `$canWrap()` / `canWrap()` from TextColumn into a `CanWrap` trait, then use across both classes.

2023-12-23 16:22 UTC, danharrin commented on packages/tables/resources/views/columns/image-column.blade.php
> +                    },
```suggestion
                    'flex-wrap' => $canWrap,
```

2023-12-23 16:23 UTC, danharrin commented on packages/tables/resources/views/columns/image-column.blade.php
> +    $wrap = $getWrap();
```suggestion
    $canWrap = $canWrap();
```

2023-12-23 16:24 UTC, danharrin reviewed
Maybe it's worth adding `wrap()` to color/icon column too?

2023-12-23 21:30 UTC, drbyte commented
> Maybe it's worth adding `wrap()` to color/icon column too?

At first glance, they seem to already have `flex-wrap` on them:
https://github.com/filamentphp/filament/blob/3.x/packages/tables/resources/views/columns/color-column.blade.php#L6

2023-12-23 21:33 UTC, drbyte commented
> Please extract `wrap()` / `$canWrap()` / `canWrap()` from TextColumn into a `CanWrap` trait, then use across both classes.

Agreed. Working on it ...

2023-12-23 23:04 UTC, drbyte commented
One problem I foresee: the default for wrapping is `false` ... but in all cases except the non-Grid table it was previously hardcoded to `true`.

To change the default to `true` is possible .... I guess then we'd just change the documentation to say "set `wrap(false)` to disable it if undesired"?

2023-12-24 05:56 UTC, drbyte commented
Icon/Color columns with `wrap()`:
<img width="313" alt="Screen Shot 2023-12-24 at 12 42 53 AM" src="https://github.com/filamentphp/filament/assets/404472/de506403-c9b7-4118-bec4-aa48a58b6b13">

Icon/Color columns with `wrap(false)`:
<img width="397" alt="Screen Shot 2023-12-24 at 12 44 02 AM" src="https://github.com/filamentphp/filament/assets/404472/10f00e6c-b9c7-4587-b3c7-a88d151db9d6">

(Screenshot note: the quantity and values of icons and colors were randomly generated, which is why they differ between screenshots, due to screen refresh. The layout is what's intended to be portrayed.)

Observation, pre-existent before this PR: When the Icon or Colour column has a title that's wide enough to permit multiple items, if `wrap()` is enabled, it will wrap based on that width, so for "perfect" wrapping which keeps only one icon or color per row, one must use a very short or blank column name/title.
Note added to docs about this.

2023-12-24 06:29 UTC, drbyte commented
Infolist Icon/Color with `wrap(false)`:
<img width="556" alt="Screen Shot 2023-12-24 at 1 26 03 AM" src="https://github.com/filamentphp/filament/assets/404472/4cd99e58-c8b8-4b2d-9fcb-aad3052fb373">

with `wrap(true)`:
<img width="545" alt="Screen Shot 2023-12-24 at 1 27 25 AM" src="https://github.com/filamentphp/filament/assets/404472/534a9793-b796-4e2d-8238-32c919db6291">

2023-12-24 17:24 UTC, danharrin requested changes
Thanks for your work on this! Sorry to be a pain, but I don't think we should actually have a configurable `wrap(false)` for infolists. It does really break the design and no-one should ever want to really use that. Can you remove that option for infolists please? The rest looks great, thanks.

2023-12-24 17:33 UTC, drbyte commented
> Sorry to be a pain, but I don't think we should actually have a configurable wrap(false) for infolists. It does really break the design and no-one should ever want to really use that.

Yes, I agree. The more I've thought about it, the more icky it feels!

Reverted.

2023-12-24 17:42 UTC, danharrin commented on packages/tables/docs/03-columns/04-image.md
> +
```suggestion

Note: the "width" for wrapping is affected by the column label, so you may need to use a shorter or hidden label to wrap more tightly.

```

2023-12-24 17:43 UTC, danharrin commented on packages/tables/docs/03-columns/04-image.md
> +When displaying the table as a Grid, images can be set to wrap if they can't fit on one line, using `wrap()`:
```suggestion
Images can be set to wrap if they can't fit on one line, by setting `wrap()`:
```

2023-12-24 17:44 UTC, danharrin commented on packages/tables/docs/03-columns/03-icon.md
> +## Wrapping the icons
```suggestion
## Wrapping multiple icons
```

2023-12-24 17:44 UTC, danharrin commented on packages/tables/docs/03-columns/04-image.md
> +## Wrapping the images
```suggestion
## Wrapping multiple images
```

2023-12-24 17:44 UTC, merged

2023-12-24 17:44 UTC, danharrin commented
Thanks for your contributions and fast iteration @drbyte!