Tagsinput: Add color and inline methods
laravel-filament/filament pull request #10587
Opened 2023-12-31 16:57 UTC by WilgnerFSDev

## Description

This PR introduces two new feature for TagsInput component, the `->color()` method (HasColor Trait) to change the color of the tags/badges and the method `->inlineInput()` to make the input inline, after the badges/tags.

- [X] Visual changes (if any) are shown using screenshots/recordings of before and after.

**Before:**
![tagsinput_before](https://github.com/filamentphp/filament/assets/32993233/ca1ff694-cdf8-4696-b8ef-53dcb535e592)

**After:**
![tagsinput_after](https://github.com/filamentphp/filament/assets/32993233/20caad1c-1218-4626-9a5c-2a5867778b57)

## Code style

- [X] `composer cs` command has been run.

## Testing

- [X] Changes have been tested.

## Documentation

- [X] Documentation is up-to-date.

2023-12-31 18:04 UTC, danharrin commented
I'm leaning towards saying no to the inline method, but I'll let Zep have the final call

2024-01-03 10:23 UTC, zepfietje commented on packages/forms/resources/views/components/tags-input.blade.php
> +                                    :color="$color"
Move this up to be the first attribute.

2024-01-03 10:23 UTC, zepfietje commented on packages/forms/resources/views/components/tags-input.blade.php
> +    $color = $getColor();
Sort this alphabetically.

2024-01-03 10:24 UTC, zepfietje requested changes
Thanks for this PR, @WilgnerFSDev!

Could you revert the "inline" changes?
I think there's more edge cases to it that need to be handled, so let's hold off on that part.

@danharrin, regarding the color API. Wouldn't it be better to support per-tag colors as we do on text columns and entries?

2024-01-03 10:27 UTC, danharrin commented
The tags are stored in Alpine on the frontend so we should not support per-tag colors ATM.

2024-01-03 21:25 UTC, WilgnerFSDev commented
> Thanks for this PR, @WilgnerFSDev!
> 
> Could you revert the "inline" changes? I think there's more edge cases to it that need to be handled, so let's hold off on that part.
> 
> @danharrin, regarding the color API. Wouldn't it be better to support per-tag colors as we do on text columns and entries?

Sure, is done.
So for now, I will create a custom field to meet the client's requirement because the TagsInput (default) in the repeater takes up too much space.

hank you for your time @danharrin and @zepfietje

2024-01-08 10:42 UTC, merged