Update table column affix helpers to support Htmlables
laravel-filament/filament pull request #10649
Opened 2024-01-04 21:11 UTC by caendesilva

Fixes https://github.com/filamentphp/filament/discussions/9729 and https://www.answeroverflow.com/m/1154022222118256700 by making so that the `->prefix()` and  `->suffix()` helpers support Htmlables like HtmlStrings.

## Description

- [ ] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [ ] `composer cs` command has been run.

## Testing

- [ ] Changes have been tested.

## Documentation

- [ ] Documentation is up-to-date.

2024-01-04 21:14 UTC, caendesilva commented on packages/tables/src/Columns/Concerns/CanFormatState.php
> +            }
Is this the best way to do this?

2024-01-04 21:25 UTC, caendesilva commented
I'm not super well versed in PHPStan. Are the test failures my fault?

2024-01-05 14:12 UTC, danharrin commented
The problem with this is that if the prefix/suffix are Htmlable, but the main content isn't, the main content is still open to XSS attacks as if it was

So when you set `isHtml`, you will also need to htmlencode the state if it is not Htmlable.

2024-01-05 14:12 UTC, danharrin requested changes
The problem with this is that if the prefix/suffix are Htmlable, but the main content isn't, the main content is still open to XSS attacks as if it was

So when you set isHtml, you will also need to htmlencode the state if it is not Htmlable.

2024-01-05 14:26 UTC, emmadesilva commented
> The problem with this is that if the prefix/suffix are Htmlable, but the main content isn't, the main content is still open to XSS attacks as if it was
> 
> So when you set isHtml, you will also need to htmlencode the state if it is not Htmlable.

Okay, how should we handle this? I think that the main content state should also support Htmlable, since the TextColumn state also supports it.

2024-01-05 15:36 UTC, danharrin commented
the main content state is the TextColumn state I was referring to

2024-01-05 15:39 UTC, caendesilva commented
> the main content state is the TextColumn state I was referring to

The TextColumn state is Htmlable, it's where I got the code for this PR from.

For example, here's the workaround I'm currently using to get a HTML suffix:

```php
Tables\Columns\TextColumn::make('name')
    ->formatStateUsing(function (string $state, Project $record): HtmlString {
        $suffix = $record->isActive() ? view('components.filament.support.active-project-badge')->render() : '';

        return new HtmlString('<span class="flex">'.$state.$suffix.'</span>');
    })
```

2024-01-05 16:57 UTC, danharrin commented
I know, but using an Htmlable prefix/suffix should not also make the main content accept HTML. Its a security issue

2024-01-05 16:59 UTC, caendesilva commented
> I know, but using an Htmlable prefix/suffix should not also make the main content accept HTML. Its a security issue

Ah, now I get what you mean. My implementation has a side effect. You're more well versed in how these internals work, what do you think is a better way of doing this?

2024-01-08 10:00 UTC, danharrin commented
When you set `$isHtml = true` for the prefix/suffix, you will also need to `e()` the main content state.

2024-01-08 10:38 UTC, merged