Added ability to customize default panel route slugs
laravel-filament/filament pull request #10742
Opened 2024-01-10 14:32 UTC by boris-glumpler

## Description

Currently the default slugs, like auth and billing, are hardcoded and cannot be changed. For the majority of apps this is probably fine, but for apps in languages other than English this can be a bit of an annoyance. This PR fixes this by making them configurable.

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

2024-01-10 15:42 UTC, danharrin requested changes

2024-01-10 15:42 UTC, danharrin commented on packages/panels/src/Panel/Concerns/HasAuth.php
Please add new methods to set the slugs, instead of adding more parameters to the existing methods, which are getting too long

2024-01-10 16:14 UTC, boris-glumpler commented on packages/panels/src/Panel/Concerns/HasAuth.php
I've created dedicated methods for each slug.

2024-01-10 18:48 UTC, devhoussam1998 commented on packages/panels/src/Panel/Concerns/HasAuth.php
you forgot `->profile()`

2024-01-11 03:15 UTC, boris-glumpler commented on packages/panels/src/Panel/Concerns/HasAuth.php
Nope, the`EditProfile` component registers its own route, so you could for example override the `getSlug()` method to set a custom slug.

2024-01-11 07:01 UTC, pxlrbt commented on packages/panels/src/Panel/Concerns/HasAuth.php
@danharrin Should we maybe move to a general `->slugs()`,`->urls()` or similar method to keep this cleaner? With the route name as the key?

```php
->slugs([
  'register' => '...',
  'reset' => '...',
])

2024-01-11 07:29 UTC, boris-glumpler commented on packages/panels/src/Panel/Concerns/HasAuth.php
Or just implement `HasRoutes` on the hardcoded route components. Would make it consistent. It could potentially be a bit confusing when there are two ways to adjust the slugs.

2024-01-11 10:45 UTC, danharrin commented on packages/panels/src/Panel/Concerns/HasAuth.php
No, I don't like the idea of an array of slugs with no autocomplete

2024-01-11 11:11 UTC, merged

2024-01-11 11:11 UTC, danharrin commented
Thanks

2024-01-11 14:00 UTC, boris-glumpler commented
Pleasure was all mine!

2024-01-11 14:12 UTC, devhoussam1998 commented
> Pleasure was all mine!

you forgot the add slug for profile?

2024-01-11 14:15 UTC, boris-glumpler commented
> you forgot the add slug for profile?

Nope, see my answer to your earlier remark.