add `extraAttributes` in Navigation Group
laravel-filament/filament pull request #10820
Opened 2024-01-15 18:19 UTC by atmonshi

## Description

Adding support for `extraAttributes`, in NavigationGroup. I need to pass some CSS classes to specific navigation group 

example usage:
```php
return $panel
->navigationGroups([
        NavigationGroup::make()
            ->label('App')
            ->extraAttributes(['class'=>'highlighted']),
        ])
```

- [ ] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

2024-01-15 18:45 UTC, atmonshi commented
running `composer cs` cases weird issues and some code deleted! so I revert it

2024-01-15 20:29 UTC, danharrin commented on packages/panels/resources/views/components/sidebar/index.blade.php
Please pass the attributes to topnav groups too

2024-01-15 20:29 UTC, danharrin commented on packages/panels/resources/views/components/sidebar/index.blade.php
And anywhere else we use the group component, if we do

2024-01-15 21:03 UTC, atmonshi commented on packages/panels/resources/views/components/sidebar/index.blade.php
the sidebar navigation (in cluster and sub navigation) dose use the `sidebar.group` but there is no way (I know of) to configure the group from the provider `navigationGroups`

2024-01-15 22:48 UTC, danharrin commented on packages/panels/resources/views/components/sidebar/index.blade.php
Let's do it anyway, I think it is possible just requires a bit of hacking

2024-01-15 22:55 UTC, atmonshi commented
all done 👍

2024-01-17 13:41 UTC, zepfietje requested changes

2024-01-17 13:41 UTC, zepfietje commented on packages/panels/resources/views/components/page/sub-navigation/sidebar.blade.php
> +            :attributes="\Filament\Support\prepare_inherited_attributes($navigationGroup->getExtraAttributeBag())"
Please move `:attributes` to be the last one in the list of attributes (like we do elsewhere).

2024-01-18 10:23 UTC, danharrin commented
I've changed my mind, the attributes that apply to a topnav dropdown would probably not be useful to apply to a sidebar group, which is used on mobile devices. Let's replace `extraAttributes()` with `extraSidebarAttributes()` and `extraTopbarAttributes()`?

2024-01-19 10:14 UTC, atmonshi commented
hey @danharrin .

np, should I create a new `trait` for `extraSidebarAttributes` and `extraTopbarAttributes`?
or add the methods in the `NavigationGroup` class

2024-01-19 10:14 UTC, danharrin commented
Please create new traits :)

2024-01-19 10:40 UTC, atmonshi commented
done, hope this what you have in mind! let me know.
also if can you double check the docs `06-navigation.md` if needs improvement :)

2024-01-19 11:53 UTC, merged

2024-01-19 11:53 UTC, danharrin commented
Thanks