Allow markAsRequired() to be used independently of required() to denote a required field.
laravel-filament/filament pull request #10929
Opened 2024-01-19 17:57 UTC by RalphMRivera

## Description

Allow markAsRequired() to be used independent of required()

In scenarios where a red asterisk must be present to denote a required field, but `->rules(['required'])` is being used instead of `->required()`, using `->markAsRequired()` will generate the red asterisk.

Example:

```php
TextInput::make('sample')
    ->rules(['required'])
    ->markAsRequired()
```

Currently, only `->markAsRequired(false)` has the effect of removing the asterisk when paired with `->required(),` but `->markAsRequired()` or `->markAsRequired(true)` have no effect even when paired with `->required()`.

This change is helpful in cases where a project ignores browser-side error handling in favor of Laravel validation, and the author wants to display a required asterisk without having to fall back on solutions such as using a `label()` that generates an HtmlString that includes a div with styling classes and an asterisk.

- [x] Visual changes (if any) are shown using screenshots/recordings of before and after.

Original code without proposed changes:

```php
TextInput::make('sample')
    ->rules(['required'])
    ->markAsRequired()
```

<img width="369" alt="image" src="https://github.com/filamentphp/filament/assets/1270019/19321c7b-f30f-4359-a60b-d0bb999698ce">

With Proposed changes:

```php
TextInput::make('sample')
    ->rules(['required'])
    ->markAsRequired()
```

<img width="364" alt="image" src="https://github.com/filamentphp/filament/assets/1270019/8713965f-2721-4a2e-8e54-d64eeea2f04f">

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

2024-01-20 12:16 UTC, danharrin requested changes

2024-01-20 12:16 UTC, danharrin commented on packages/forms/resources/views/components/field-wrapper/label.blade.php
> +        {{ $slot }}@if ($required && $isMarkedAsRequired && ! $isDisabled || ! $required && $isMarkedAsRequired && ! $isDisabled)<sup class="text-danger-600 dark:text-danger-400 font-medium">*</sup>
Isn't that just doing this?

```suggestion
        {{ $slot }}@if (($required || $isMarkedAsRequired) && (! $isDisabled))<sup class="text-danger-600 dark:text-danger-400 font-medium">*</sup>
```

2024-01-20 22:04 UTC, RalphMRivera commented
I committed the refactoring recommended by @danharrin. Thanks!

2024-01-20 22:19 UTC, merged

2024-01-20 22:19 UTC, danharrin commented
Thanks

2024-01-21 07:05 UTC, misaf commented
after recent update all Forms\Components Field has an asterisk !

2024-01-21 13:02 UTC, RalphMRivera commented
I've created a new [Pull Request](https://github.com/filamentphp/filament/pull/10966) to revert the code while I work on an alternate solution.