feat: Allow columns to be omitted from exports by default.
laravel-filament/filament pull request #11067
Opened 2024-01-25 17:14 UTC by morphsteve

## Description

Currently the modal for the new export action has all columns selected by default. In the case where an export includes a column that is only occasionally needed, it would be convenient for it to be _deselected_ by default.

This PR makes a simple modification to `ExportColumn` and `CanSelectRecords`, adding a `$defaultEnabled` property and appropriate methods (there may be a more suitable name for this) to allow the default state of a column to be configured.

- [x] Visual changes (if any) are shown using screenshots/recordings of before and after.

(No visual changes.)

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

(Changes tested manually.)

## Documentation

- [x] Documentation is up-to-date.

2024-01-26 11:21 UTC, danharrin requested changes
Please rename this API to just `default()`, `isDefault()` and `$isDefault`.

2024-01-30 09:30 UTC, morphsteve commented
Thanks @danharrin, however `default()` collides with `HasCellState::default()`.

2024-01-31 09:14 UTC, danharrin commented
Ah, gotcha. Can we have `enabledByDefault()`, `$isEnabledByDefault` and `isEnabledByDefault()` then please?

2024-01-31 09:30 UTC, morphsteve commented
Done @danharrin.

2024-01-31 09:30 UTC, danharrin requested changes

2024-01-31 09:30 UTC, danharrin commented on packages/actions/src/Exports/ExportColumn.php
> +        return $this->evaluate($this->isEnabledByDefault) ?? true;
```suggestion
        return (bool) $this->evaluate($this->isEnabledByDefault)
```

2024-01-31 09:30 UTC, danharrin commented on packages/actions/src/Exports/ExportColumn.php
> +        $this->isEnabledByDefault = $isEnabledByDefault;
```suggestion
    public function enabledByDefault(bool | Closure $condition): static
    {
        $this->isEnabledByDefault = $condition;
```

2024-01-31 09:32 UTC, merged

2024-01-31 09:32 UTC, danharrin commented
Thanks!