Custom Component Style Updates
laravel-filament/filament pull request #11217
Opened 2024-02-01 18:51 UTC by tnylea

Hey guys 👋 this is a very small PR; however, I may have a few more down the road 😊

## Description

I am trying to add [custom styles to a few of the filament components](https://filamentphp.com/docs/3.x/support/style-customization#discovering-hook-classes) and not able to make some modifications. This PR is an attempt to try make those mods possible. There are only 2 fixes in this PR.

### 1. The Button/index component

Inside of the Button component you are displaying the text/slot content in the component like so:

```
<span
    @if ($hasFormProcessingLoadingIndicator)
        x-show="! isProcessing"
    @endif
    class="{{ $labelClasses }}"
>
    {{ $slot }}
</span>
```

However, if I only wanted to display a button with an icon it doesn't look right because the parent container has a `.space-x` utility class, and the button looks like this:

![jenky-button](https://github.com/filamentphp/filament/assets/601261/ab64637f-7b82-4fb3-abab-6685914b1a6d)

I thought to myself... No problem. I'll just use the CSS `:empty` property to hide the `<span>` element if it is empty; however, the problem is that when the button text is empty the white-space inside that element is being rendered in the DOM like so:

```
<span class="fi-btn-label">
        
    </span>
```

The CSS `:empty` property counts whitespace as being content so therefore, it is not empty. So, if we change that line to be:

```
<span
    @if ($hasFormProcessingLoadingIndicator)
        x-show="! isProcessing"
    @endif
    class="{{ $labelClasses }}"
>{{ $slot }}</span>
```

I can add the following CSS:

```
.fi-btn-label:empty{
    @apply hidden;
}
```

And now that icon button is looking pretty good:

![good-button](https://github.com/filamentphp/filament/assets/601261/6580ac59-fc20-4dea-a35a-3dd360ff2c7a)

This was the only alternative that I could find for stylizing this correctly, but let me know if there's another way that I could be doing this.

### 2. The Badge Component

I can't seem to find a way to override the styles in the badge component for a particular color without a class that specifies the color:

```
is_string($color) ? "fi-badge-color-{$color}" : null,
```

This will allow me to add custom styles to that badge for that specific color.

I did see that this is available in the button component and unfortunately seen that there was a deprecation notice for this class, on this line here (https://github.com/filamentphp/filament/blob/3.x/packages/support/resources/views/components/button/index.blade.php#L60). Are you guys going to remove that from the button? I actually think it's a great class to have for adding custom CSS to each button color and I would love to have it in the badge component as well.

## Code style

- [x] `composer cs` command ran successfully

## Testing

- [ ] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.
  No additional documentation is needed for this use-case.

Thanks so much guys for all the hardwork you do 🙏

Appreciate it!

Let me know if you have any follow-ups, or have an answer about the deprecation of those classes 😊

2024-02-02 11:29 UTC, danharrin commented
Hey! For the button label, try the `label-sr-only` attribute. IMO you should still define the label, and then use this attribute, so that it is accessible.

Or you could just go with the icon-button component instead?

2024-02-02 14:27 UTC, tnylea commented
@danharrin Thanks for the comment!

Ok, I can do that with the Icon Button. That should resolve the issue for that component. How about for the button. Are you guys planning on removing this `is_string($color) ? "fi-btn-color-{$color}" : null,`

Is it possible to have this added to the badge class:

```
is_string($color) ? "fi-badge-color-{$color}" : null,
```

I've just updated the PR to only include that custom style for the badges as I can use the Icon button for Button that only has an icon.

Thanks so much!

2024-02-03 10:08 UTC, zepfietje commented
For v4 I'm planning to support icon-only buttons for non-icon-buttons (so regular buttons and the plain variant to be added: https://github.com/filamentphp/filament/issues/10558).
Let's not touch that part for now to prevent breaking changes.

As for the color classes, could you elaborate on your specific use case?
I've thought about adding `fi-color-purple` classes for named colors, but in many cases the current `fi-color-custom` classes should suffice.
Let me know.

2024-02-07 16:47 UTC, tnylea commented
Hey @zepfietje 

Thanks for getting back to me 😊. So, I'm trying to create a custom design system built on top of the Filament components. In this specific design system, I have 3 styles of badges. `primary`, `secondary`, and `danger`. So, I want to add some custom styles to each of those badges; however, there isn't a way to differentiate those elements based on the specific color.

Here is a screenshot of our current badge component with the current code:

![cannot](https://github.com/filamentphp/filament/assets/601261/34011d30-fd23-4ac0-a44a-3595d1952f98)


As you can see, there is not a specific class that I can use to stylize our `primary` vs our `secondary` badge component.

With the changes that I have suggested, users will be able to stylize the badge based on a specific class:

![can-1](https://github.com/filamentphp/filament/assets/601261/6bab57aa-39a8-4f77-a9e8-8a5baf133114)

![can-2](https://github.com/filamentphp/filament/assets/601261/6cbf380d-7f8c-4ead-8b28-b61ee6b97ac7)

We could always just create our own `badge` component, but instead want to use Filament components and override the styles with some custom CSS, but the way that it currently stands it's not possible to do so without these classes.

Let me know if that makes sense and/or you have any other questions. Really appreciate it 🙏

Look forward to hearing from you soon 😊

2024-02-08 10:21 UTC, zepfietje requested changes
Thanks for clarifying, @tnylea.

Honestly I don't think the color classes should be used to create different "styles" of components.

You may want to consider creating a new API for your project like "variant" instead.

However, I'm open to adding `fi-color-primary`, `fi-color-blue`, etc. classes for named colors to all places where we currently have `fi-color-custom` and `fi-color-gray`.

Please rework this PR to add this to the entire codebase. If you don't want to work on it, feel free to close the PR. 🙂

2024-02-08 21:53 UTC, tnylea commented
Thanks for the reply @zepfietje, I'll be updating the PR to include that class for all components in the next few days 👏

Appreciate it and I'll talk to you soon!

2024-02-10 13:20 UTC, danharrin commented
Not sure if this has been covered, but I think the color classes can be generalised instead of component-specific to reduce their length

2024-02-10 13:48 UTC, zepfietje commented
Yeah they should just be `fi-color-name` as per my comment.
Some old classes may still exist, but they should be marked as deprecated, which I've probably already done for all of them.

2024-02-10 13:49 UTC, zepfietje commented
Also, I think colors from the default Tailwind palette should get a named class when used like `Color::Purple` (`fi-color-purple`).

2024-02-11 17:46 UTC, danharrin commented
> Also, I think colors from the default Tailwind palette should get a named class when used like `Color::Purple` (`fi-color-purple`).

I think that would be tricky, they are just class constants backed by arrays. If they are registered as named colors then its easy, but lets not worry about that.

2024-02-12 09:31 UTC, zepfietje commented
> I think that would be tricky, they are just class constants backed by arrays. If they are registered as named colors then its easy, but lets not worry about that.

Yeah I know, maybe something for the future.

2024-02-12 13:26 UTC, rcostadev reviewed
is good

2024-02-15 22:26 UTC, tnylea commented
Hey guys, just wanted to keep you updated. I've made sure to add all the suggested changes. I was going to put together a storybook of most of the Filament components and test these out. I'll also see about adding a few updates to the docs to let users know about the color classes they can use.

Thanks a ton. Hoping to wrap this up tomorrow 😉

2024-02-16 07:37 UTC, zepfietje requested changes

2024-02-16 07:37 UTC, zepfietje commented on packages/support/resources/views/components/button/index.blade.php
> +            is_string($color) ? "fi-color-{$color}" : null,
Old class needs to stay for BC.

2024-02-16 07:37 UTC, zepfietje commented on packages/support/resources/views/components/dropdown/header.blade.php
> +                is_string($color) ? "fi-color-{$color}" : null,
Please add to parent component instead.

2024-02-16 07:37 UTC, zepfietje commented on packages/support/resources/views/components/link.blade.php
> +        is_string($color) ? "fi-color-{$color}" : null,
Should be on parent.

2024-02-18 23:27 UTC, tnylea commented on packages/support/resources/views/components/button/index.blade.php
> +            is_string($color) ? "fi-color-{$color}" : null,
Added that back 😉

Thanks!

2024-02-18 23:29 UTC, tnylea commented
@zepfietje Just went ahead and made those updates.

Let me know if there are anything else that needs to change. I've tested on my end and these custom color classes should be working fine now with this PR allowing me to customize them better.

Really appreciate it! Talk to you soon.

2024-02-28 12:32 UTC, zepfietje approved these changes, later dismissed

2024-02-28 12:33 UTC, zepfietje commented
I've added a lot of missing `fi-color-*` classes, and made sure `fi-color-gray` didn't have duplicates in the codebase. Should be ready to be merged now.

Thanks, @tnylea!

2024-02-28 12:48 UTC, merged