Allow checking to see if a record can be deleted before deleting
laravel-filament/filament pull request #11349
Opened 2024-02-10 18:28 UTC by binaryfire

Solves: https://x.com/maurozadu/status/1751351926711545863?s=20

Currently there's no clean way to check for integrity constraint violations before deleting a record. Hiding the action can lead to a confusing UX because it's not clear to the user why the delete button is there for some records and not for others. Using `before` works but it means repeatedly creating the same boilerplate.

This PR adds a convenient way of running a check before deletions occur, and showing a customisable notification if when it isn't allowed:

```
DeleteAction::make()
      ->allowedToDelete(fn ($record) => !str_starts_with($record->first_name, 'A'))
      ->deleteNotAllowedNotificationTitle('Cannot delete this member')
      ->deleteNotAllowedNotificationBody(fn ($record) => "You cannot delete {$record->full_name} because their first name starts with 'A'."),
```

<img width="321" alt="image" src="https://github.com/filamentphp/filament/assets/5361908/bce127a3-94ff-448d-9e57-56eb680921c2">

2024-02-10 18:29 UTC, binaryfire commented
This is still WIP. I need to make the same changes to the table action and add some documentation.

2024-02-10 20:28 UTC, binaryfire commented
Table delete actions and docs updated, all good for review.

2024-02-11 18:15 UTC, danharrin requested changes
Please alter the behaviour so the notification shows instead of the modal

2024-02-11 19:00 UTC, binaryfire commented
> Please alter the behaviour so the notification shows instead of the modal

Seems like my `isDeletable()` trait method is only evaluated inside `$this->action()`. Why would that be? I tried doing the following but it always returns true when used in this location:

```
if ($this->isDeletable()) {
    ray($this->isDeletable());

    $this->modalHeading(fn (): string => __('filament-actions::delete.single.modal.heading', ['label' => $this->getRecordTitle()]));

    $this->modalSubmitActionLabel(__('filament-actions::delete.single.modal.actions.delete.label'));

    $this->modalIcon(FilamentIcon::resolve('actions::delete-action.modal') ?? 'heroicon-o-trash');

    $this->requiresConfirmation();
}
```

2024-02-11 19:54 UTC, danharrin commented
Too early in the lifecycle of the class to to it in `setUp()`, that runs when the class is constructed, even when its rendered and not clicked. You'd need to add a `modalHidden()` condition I think, and keep the code in `action()` or `before()`. `before()` might be better tbh as then it is overridable individually, then you just call `$action->halt()` too

2024-02-11 21:18 UTC, binaryfire commented
`modalHidden()` is called before `before()` so I just used that. It sets a property which is checked in `action()` so that `isDeletable()` is only evaluated once.

2024-02-12 03:38 UTC, wychoong commented
Maybe 

```php
 ->notDeletableNotification(fn ($notification) => …)

```

2024-02-12 03:55 UTC, binaryfire commented
Do you mean define the whole notification manually eg. `Notification::make()->`…. ? The idea here is to provide the same clean DX as `->modalHeading()`, `->modalDescription()` etc. The title and body both accept closures so it’s pretty easy to customize the notification.

2024-02-12 07:38 UTC, wychoong commented
Something like this

https://github.com/filamentphp/filament/blob/e07cc0fd787c3767ab1034c9a0096490626fb29d/packages/actions/src/Concerns/CanNotify.php#L33

2024-02-12 08:23 UTC, binaryfire commented
So you want to be able to use custom notifications rather than being stuck with a `danger` notification with only a customizable title and body? Yeah that's probably better. Eg. if you were doing `->deletable(fn ($record) => $record->teams->isEmpty())` it might be nice to include a notification action that takes you to that user's teams.

What do you think @danharrin?

2024-02-12 08:25 UTC, danharrin commented
At that level of customization, I do not really understand the point of the new feature when it could be accomplished manually in roughly the same number of lines

2024-02-12 08:33 UTC, binaryfire commented
Actually your point about skipping the modal was a good one - the UX is much better. You can't do that by just using `->before()`. It would get kinda messy trying to do that manually.

Anway, I think the vast majority of people would be happy with the current implementation. And if you need more you can still go manual.

2024-02-12 08:36 UTC, wychoong commented
> rather than being stuck with a `danger` notification with only a customizable title and body?

Yes

> it could be accomplished manually in roughly the same number of lines

But not always need to customize everything down to the color. And the api will similar with Action’s notification without implementing all notification api

2024-02-12 08:49 UTC, danharrin commented
```php
->modalHidden(fn ($record) => $record->teams->isEmpty())
->before(fn ($record, $action) => $record->teams->isEmpty() && Notification::make()
    ->title('Delete?')
    ->danger()
    ->send() && $action->halt())
```

I really don't think it's that bad tbh

2024-02-12 08:51 UTC, danharrin commented
And then users can remove the `modalHidden()` if they want to show the modal anyway, instead of forcing that behaviour, you know? Just feels like it's not enough complexity to warrant an abstraction, but you could create a macro for it!

2024-02-12 08:51 UTC, closed without merging

2024-02-12 08:51 UTC, binaryfire commented
Yeah that's fair. No worries.