Add footer for Section Blade component
laravel-filament/filament pull request #11457
Opened 2024-02-17 09:49 UTC by mischasigtermans

## Description

This pull request adds a new footer section to the Section Blade component. This enhancement aims to improve the structure and flexibility of content presentation, allowing developers to include additional information, links, or actions at the bottom of each section.

![screenshot-001252 (2024-02-17)@2x](https://github.com/filamentphp/filament/assets/22501510/b2555dd2-110d-44ba-bf9f-5199bc583a46)

## Code style

- [x] `composer cs` command has been run.

## Testing

Tested to work with `aside`, `collapsible` and `compact`.

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

2024-02-17 12:44 UTC, zepfietje requested changes

2024-02-17 12:44 UTC, zepfietje commented on packages/support/resources/views/components/section/index.blade.php
> +                        'fi-modal-footer mt-6 border-t border-gray-200 dark:border-white/10',
Please use correct `fi-*` CSS class naming related to this component please. 🙂

2024-02-20 12:28 UTC, mischasigtermans commented
@zepfietje I've discovered the behavior of the `headerActions` is not consistent in every case. I've changed the behavior and made sure works correctly in every case. Also made sure that when `collapsible` is set, the `headerActions` don't trigger collapsible.

![screenshot-001268 (2024-02-20)@2x](https://github.com/filamentphp/filament/assets/22501510/7c0b0300-4310-4b9a-b7c9-8dc2e56ef1a7)

2024-02-20 14:30 UTC, zepfietje commented
@mischasigtermans, could you revert the header action changes and re-apply them in a separate PR?

There's been a couple times those actions broke because not all cases were accounted for, so I'd like to review it properly separately from the footer PR.

Thanks!

2024-02-21 21:50 UTC, mischasigtermans commented
@zepfietje Done. Just tested all possibilities again for the footer. Let me know if I missed anything.

2024-03-01 16:11 UTC, zepfietje requested changes
If we're going to add footer actions support to the section Blade component, I think we need support for adding footer actions in the object API too. Could you add a `footerActions()` API similarly to https://github.com/filamentphp/filament/pull/9161?

2024-03-01 17:08 UTC, mischasigtermans commented
Not something I can do. Maybe @danharrin can squeeze it in?

2024-03-02 13:58 UTC, zepfietje commented
What is unclear to you, @mischasigtermans?
Should be very similar to https://github.com/filamentphp/filament/pull/9161 if I'm correct. 🙂

2024-03-02 14:07 UTC, mischasigtermans commented
It's a time management thing. 😉

2024-03-03 10:16 UTC, zepfietje commented
I understand, though I'm not sure if we should merge this in already without forms and infolists API support.

You're lucky that I just found the need for this myself. 😜
Will be taking over this PR, reviewing it and adding support for the new APIs. 👍

2024-03-03 13:59 UTC, zepfietje commented
Replaced by https://github.com/filamentphp/filament/pull/11662, since I had to revert too many changes of the original PR. 🙂

2024-03-03 13:59 UTC, closed without merging