Add uncontained section design
laravel-filament/filament pull request #11464
Opened 2024-02-17 18:32 UTC by divdax

## Description

Extended Form Section with `->minimal()` for a minimalistic style.

```php
Section::make('Heading')->minimal()
```

| default | `->minimal()` |
|--------|--------|
| <img width="837" alt="image" src="https://github.com/filamentphp/filament/assets/1456739/f2163105-8876-4466-93cd-796206fa6c05"> | <img width="846" alt="image" src="https://github.com/filamentphp/filament/assets/1456739/b55efe08-067a-4fba-8adb-3d2bffa6bffb"> | 

### or maybe... 

```php
->compact(minimal: true)
->compact(basic: true)
```

This could be useful if someone wants to use a self-styled component (not just the section) without removing all styles:
```php
->compact(styles: false)
```

What do you think?

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [ ] Documentation is up-to-date.

2024-02-21 22:10 UTC, mischasigtermans commented
This would also be nice for a repeater. Here's an example of a repeater within a section. A _minimal_ style would be nice.
![screenshot-001294 (2024-02-21)@2x](https://github.com/filamentphp/filament/assets/22501510/7ec052f3-4628-4f93-a6f2-63de8a246e87)

2024-02-28 13:09 UTC, zepfietje requested changes
@divdax, could you rework this to `contained(false)`, just like already exists for wizard, tabs and others?

2024-02-28 14:28 UTC, divdax commented
> @divdax, could you rework this to `contained(false)`, just like already exists for wizard, tabs and others?

jo 👍

2024-02-28 20:50 UTC, divdax commented
@zepfietje section is now using CanBeContained trait.

2024-02-29 17:15 UTC, zepfietje requested changes

2024-02-29 17:15 UTC, zepfietje commented on packages/support/resources/views/components/section/index.blade.php
> +                false => !$contained ? '' : 'rounded-xl bg-white shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10',
Could you please simplify the ternaries by not negating them?

2024-02-29 22:46 UTC, divdax commented on packages/support/resources/views/components/section/index.blade.php
> +                false => !$contained ? '' : 'rounded-xl bg-white shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10',
done

2024-03-01 16:01 UTC, zepfietje requested changes

2024-03-01 16:01 UTC, zepfietje commented on packages/forms/resources/views/components/section.blade.php
>      :compact="$isCompact()"
Please sort alphabetically :)

2024-03-01 16:01 UTC, zepfietje commented on packages/support/resources/views/components/section/index.blade.php
> +    'contained' => true,
`n` comes after `m` ;)

2024-03-01 16:01 UTC, zepfietje commented on packages/support/resources/views/components/section/index.blade.php
>              },
Thinking about it once more, maybe it's easier to maintain if we got rid of the match expression and used two separate array items instead. One for the `fi-aside` with a condition as the value and then the other one for contained non-aside. Not sure if that explanation is clear? 😂

2024-03-01 16:01 UTC, zepfietje commented on packages/support/resources/views/components/section/index.blade.php
> +                    false => ! $contained ? 'py-4' : 'px-6 py-4',
Could you split these into separate array items too?
Also, is the vertical padding needed when uncontained?

2024-03-01 16:01 UTC, zepfietje commented on packages/support/resources/views/components/section/index.blade.php
> +                'rounded-xl bg-white shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10' => $aside && (! $minimal),
Looks `$minimal` was forgotten during the rework?

2024-03-01 16:01 UTC, zepfietje commented on packages/support/resources/views/components/section/index.blade.php
> +                    false => ! $contained ? 'pt-4' : 'p-6',
Also get rid of the match expression here, because this gets quite unreadable otherwise. 🙂

2024-03-01 18:11 UTC, saade commented
@zepfietje can we remove the border under the header too? or perhaps only apply if its collapsible.

2024-03-02 13:57 UTC, zepfietje commented
Still going to do a visual review after the code review, and the border is one thing for sure that I'm still debating.

2024-03-07 19:09 UTC, zepfietje requested changes
@divdax, could you merge 3.x into this PR's branch and add support for the recently introduced section footer actions?

2024-03-08 00:43 UTC, divdax commented
@zepfietje i did the refactor. looking into the footer actions this weekend (hopefully)

// edit: here an example why i used the border. Also looks better when using heading + description.
Do you know if there are any plans for unstyled elements using just the basic fi-* classes which i think are unstyled and just for reference? What i mean by that: Would be cool to give every element `->unstyled()` to get rid of every css class so we could write custom css without having to override all filament classes. I hope you understand what i mean. 🙃

<img width="979" alt="image" src="https://github.com/filamentphp/filament/assets/1456739/ae5f5646-8c7d-43ab-abe7-3a249ea1a74e">

2024-03-09 01:17 UTC, divdax commented
@zepfietje merged 3.x and updated footer classes.

2024-03-09 18:58 UTC, ralphjsmit commented
Looking great, nice work Heiko! Been missing this for years.

2024-03-11 13:04 UTC, zepfietje commented
Could you guys provide some context on how you're using uncontained sections, @divdax @ralphjsmit? Would help me in reviewing the design in this PR.

2024-03-11 18:17 UTC, ralphjsmit commented
Some examples that I do remember are e.g. inside a modal on a white area where you don't want to have the card/another border for the content. Just a simple heading/description/icon to distinguish on a page would be good.
Or if you want to have the form components om the default gray Filament panel background (so not inside cards/sections), but that's impossible with the current Section design. 

But mainly just serving as a visual indicator of splitting up the page without needing an indent/border/white background.

2024-03-11 22:04 UTC, divdax commented
I often use sections in modals to save space and create a cleaner look. When a section is within another "container" i usually don't need a second box. Used filament forms standalone on many pages where i placed the form in an already styled container.

**idea:**
It would be great to deactivate all CSS classes with styles for components, leaving only the reference classes (e.g. .fi-section-content) without styles. This way, users can style from scratch instead of having to override existing styles.
Currently, you have to override all applied styles when writing a theme. Next step could be something like a global config e.g. `Component::disableStyles()`.

2024-03-12 15:42 UTC, zepfietje commented
> **idea:** It would be great to deactivate all CSS classes with styles for components, leaving only the reference classes (e.g. .fi-section-content) without styles. This way, users can style from scratch instead of having to override existing styles. Currently, you have to override all applied styles when writing a theme. Next step could be something like a global config e.g. `Component::disableStyles()`.

This is already one of the main goals for v4. 👍

2024-03-12 15:44 UTC, zepfietje requested changes
@divdax, I've done some more research about when to use uncontained sections and have come to the conclusion that it's best to remove the border below the header and above the footer too. Could you update the PR so I can do a proper final review? 🙂

2024-03-22 09:00 UTC, zepfietje commented
Hey @divdax, are you able to finish this PR?

2024-04-04 15:22 UTC, saade commented
@zepfietje i know this can be achieved with css for now, but i can take his work and apply the requested changes if you wish... i'm kinda needing that too to clean up some code at my end.

2024-04-04 20:50 UTC, zepfietje commented
Yeah, please go ahead @saade, since this PR has been stale for a while now.

2024-04-08 13:08 UTC, divdax commented
@zepfietje i was on holidays. 🏖️  not sorry 😅

2024-04-08 15:29 UTC, zepfietje commented
No worries, @divdax!
We just have some default intervals at which we check in on the status of PRs to keep it all maintainable. 🙂

2024-04-09 14:22 UTC, saade commented
@divdax i didnt started yet, lmk if you want to continue with your work

2024-04-09 14:41 UTC, zepfietje commented
Yeah let us know, @divdax, then I can reopen your PR.

2024-04-09 15:14 UTC, divdax commented
@zepfietje i'll take a look after work and make the final touches. i think it's just the heading border i have to remove.

**// edit:** Border removed when contained = false

2024-04-09 19:49 UTC, zepfietje commented
Thanks, @divdax!
So this is ready for final review now?

2024-04-10 08:12 UTC, divdax commented
@zepfietje yes

2024-05-06 17:01 UTC, divdax commented
@zepfietje dumdidumm 👀😬

2024-05-07 07:17 UTC, zepfietje commented
@divdax, I've been extremely busy working towards the launch of [Whizzy](https://whizzy.dev) and have lost 25% of my GitHub Sponsors, so spending more time on Filament than I already do has been hard. I'll get back to reviewing this though! 😄

2024-05-07 07:19 UTC, zepfietje requested changes

2024-05-07 07:19 UTC, zepfietje commented on packages/support/resources/views/components/section/index.blade.php
> +            'rounded-xl bg-white shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10' => $contained,
This doesn't seem right?
The previously `false` match arm only has a `$contained` condition here.

2024-05-21 06:43 UTC, zepfietje commented
@divdax "dumdidumm". 😂
Could you have a look at my change request from two weeks ago? 🙂

2024-05-29 12:27 UTC, zepfietje commented
@divdax, are you still interested in finishing this PR?
Otherwise I may have to close it in a week and get back to it myself at a later time.

2024-06-08 10:46 UTC, closed without merging

2024-06-08 10:47 UTC, zepfietje commented
Closing this PR and picking the feature up myself since there's missing cases that need to be handled.