Update CanGroupRecords.php
laravel-filament/filament pull request #11667
Opened 2024-03-04 07:02 UTC by misaf

This pull request refines the behavior of the applyGroupingToTableQuery method to provide better control over eager loading, specifically when isTableReordering is enabled.

## Description

- [ ] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [ ] `composer cs` command has been run.

## Testing

- [ ] Changes have been tested.

## Documentation

- [ ] Documentation is up-to-date.

2024-03-04 07:32 UTC, zepfietje requested changes
Please fill out the entire pull request template (as stated in the template) and make sure `composer cs` has been run to fix code style issues.

2024-03-04 07:58 UTC, misaf commented
This important bug involves an attempt to implement lazy loading, which could result in errors.

Additionally, I ran composer cs to fix coding style issues

2024-03-04 11:40 UTC, danharrin commented
I do not understand. While reordering, the group headings and descriptions are not visible. So why does the data need to be eager loaded?

2024-03-04 17:55 UTC, misaf commented
Thank you for your feedback,

When reordering, our intention is to sort the table by column name and then respond to the user with the grouped data. Currently, when using grouping, applyEagerLoading is applied without any issues. However, when we introduce reordering into the mix, this method first checks if reordering is in progress. If it is, it returns the query without applying eager loading. Consequently, in the response, we are using productCategory.name without eager loading, which leads to performance issues and potential N+1 problems.

To resolve this, we need to ensure that eager loading is applied consistently, even during reordering, to maintain optimal performance and data integrity.

I've attached two images showing the SQL query logs during the reordering process. These logs demonstrate that without eager loading, we encounter the N+1 issue, resulting in additional queries and potential performance bottlenecks.


![Screenshot 2024-03-04 at 21 06 14](https://github.com/filamentphp/filament/assets/8195685/ec7c7b6d-6af7-4cfb-b98d-930c7fee39b5)
![Screenshot 2024-03-04 at 20 51 45](https://github.com/filamentphp/filament/assets/8195685/65ccd9bd-92a9-4bd1-afa4-73e94a51f02a)

2024-03-04 17:58 UTC, danharrin commented
I still do not understand, which part of Filament do the queries originate from if the group headings are not displayed while reordering? Surely if the group headings are hidden while reordering, they do not need to display any data

2024-03-04 18:38 UTC, misaf commented
if the group headings are indeed visible during reordering, then the data associated with those groups still needs to be accurately loaded and displayed to the user.

I've uploaded a new video to better illustrate the situation. @danharrin 

https://houshang-flowers.com/screen.mov

2024-03-04 18:46 UTC, danharrin commented
How did you make group headings visible while reordering? I thought that was disabled

2024-03-04 18:51 UTC, misaf commented
I didn't enable group headings during reordering intentionally. It seems to be the default behavior.

2024-03-06 11:15 UTC, danharrin commented
I've made it so that group headings aren't present while reordering.

2024-03-06 11:15 UTC, merged