Add `multiple()` functionality to AttachAction and AssociateAction
laravel-filament/filament pull request #11913
Opened 2024-03-18 13:11 UTC by W1-PopelierE

## Description
In discussion #11894, I proposed adding ﻿->multiple() to the AttachAction. @danharrin approved, with the condition of adding it to AssociateAction as well. This enhancement enables attaching or associating using a multiple select.

- [x] Visual changes (if any) are shown using screenshots/recordings of before and after.

Not really a new style but a screenshot won't hurt.
<img width="502" alt="image" src="https://github.com/filamentphp/filament/assets/17490821/c54f5c54-a71e-444b-ad9f-b30fb95b36f5">

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

I was unsure where to add the tests for AttachActions and AssociateActions. However, since there were separate tests for BulkActions, I decided to make these tests separate as well.
## Documentation

- [x] Documentation is up-to-date.

2024-03-18 22:54 UTC, danharrin commented on packages/panels/docs/03-resources/07-relation-managers.md
> +### Multi-select
```suggestion
### Attaching multiple records
```

2024-03-18 22:54 UTC, danharrin commented on packages/panels/docs/03-resources/07-relation-managers.md
> +### Multi-select
```suggestion
### Associating multiple records
```

2024-03-18 22:58 UTC, danharrin requested changes
Thanks for the effort here! I have some comments about the testing helpers introduced

2024-03-18 22:58 UTC, danharrin commented on packages/tables/.stubs.php
I think some of these testing helpers probably aren't required and can be replicated easily:

`->assertTableActionExists(AttachAction::class)`
`->assertTableActionDoesNotExist(AttachAction::class)`
`->assertTableActionExists(AssociateAction::class)`
`->assertTableActionDoesNotExist(AssociateAction::class)`

And I think we can alter `assertTableActionExists()` to accept a second parameter, `$checkActionUsing`, inspired by `assertTableColumnExists()`. Then you could do:

`->assertTableActionExists(AttachAction::class, fn (AttachAction $action) => $action->isMultiple())` to ensure it is multiple, which is more flexible

2024-03-19 15:58 UTC, W1-PopelierE commented on packages/tables/.stubs.php
I made some changes, not really sure if this is what you meant though...

2024-03-20 09:27 UTC, merged

2024-03-20 09:28 UTC, danharrin commented
Thanks!