Fix/missing alt for profile image
laravel-filament/filament pull request #12082
Opened 2024-03-28 21:46 UTC by mikeslinkman

## Description

Adds the alt attribute for the avatar of a user based on the users name.

## Visual changes

No visual changes

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-03-29 08:54 UTC, zepfietje commented
Wouldn't it be ok to just use the user name without any prefix?
Also, this should probably be added to the tenant avatar in the tenant menu too.

2024-03-29 09:47 UTC, mikeslinkman commented
> Wouldn't it be ok to just use the user name without any prefix? Also, this should probably be added to the tenant avatar in the tenant menu too.

It would be an improvement compared to the current situation, but we would leave the user "guessing" what the context for the image is. Ideally we would add the additional context, and I would be willing to add more translations by using google translate but first wanted to get a initial response. I'll add it for the tenant variant as well once we've settled on the way we will handle the translations (if we handle these)

2024-03-29 11:09 UTC, zepfietje commented
Thanks for clarifying, @mikeslinkman.
I agree, though we should discuss if avatar / profile picture / profile photo or something else fits best in this case. Kinda tricky since it may depend on the actual application.

Also, after this PR, when we add it to tenant avatars too, we also update `packages/panels/resources/views/components/logo.blade.php` to user a "logo" suffix.

2024-03-29 11:21 UTC, mikeslinkman commented
> Thanks for clarifying, @mikeslinkman. I agree, though we should discuss if avatar / profile picture / profile photo or something else fits best in this case. Kinda tricky since it may depend on the actual application.
> 
> Also, after this PR, when we add it to tenant avatars too, we should also update `packages/panels/resources/views/components/logo.blade.php` to use a "logo" suffix.

Yes, I can totally add it over there as well. I'm open to any of those but I have a slight preference for using 'Avatar' since this is also the best description when it is not an actual photo but instead shows the initials of the authenticated user. But also happy to explore other options

2024-03-29 23:19 UTC, danharrin commented
+1 for avatar, its the terminology we use internally anyway

2024-03-29 23:20 UTC, danharrin commented on packages/panels/resources/views/components/avatar/user.blade.php
> +    :alt="__('filament-panels::layout.top_bar.avatar', ['user' => filament()->getUserName($user)])"
Can you refactor the translation to use `filament-panels::layout.avatar.alt` please?

2024-03-29 23:20 UTC, danharrin commented on packages/panels/resources/lang/nl/layout.php
> +    ],
Please remove new lines in arrays when there is no nesting, as per the other instances in these files

2024-03-29 23:24 UTC, danharrin requested changes
While this is open, please also apply this so the tenant avatar, which can use the same translation string

2024-03-30 08:41 UTC, zepfietje commented
> While this is open, please also apply this so the tenant avatar, which can use the same translation string

And add the "logo" suffix/prefix to the brand logo component alt.

2024-03-30 09:15 UTC, danharrin commented
For that one, the translation string can be layout.logo.alt I think

2024-03-30 10:45 UTC, zepfietje commented on packages/panels/resources/lang/en/layout.php
> +        'alt' => 'Avatar representing :user',
```suggestion
        'alt' => 'Avatar of :user',
```

2024-03-30 10:45 UTC, zepfietje commented on packages/panels/resources/lang/nl/layout.php
> +            'alt' => 'Avatar vertegenwoordigt :user',
```suggestion
            'alt' => 'Avatar van :user',
```

2024-03-30 10:46 UTC, zepfietje commented on packages/panels/resources/lang/en/layout.php
> +        'alt' => 'Avatar of :user',
```suggestion
        'alt' => 'Avatar of :name',
```

2024-03-30 10:46 UTC, zepfietje commented on packages/panels/resources/lang/nl/layout.php
> +            'alt' => 'Avatar van :user',
```suggestion
            'alt' => 'Avatar van :name',
```

2024-03-30 10:47 UTC, zepfietje commented on packages/panels/resources/views/components/avatar/tenant.blade.php
> +    :alt="__('filament-panels::layout.avatar.alt', ['user' => filament()->getTenantName($tenant)])"
```suggestion
    :alt="__('filament-panels::layout.avatar.alt', ['name' => filament()->getTenantName($tenant)])"
```

2024-03-30 10:47 UTC, zepfietje commented on packages/panels/resources/views/components/avatar/tenant.blade.php
>      :src="filament()->getTenantAvatarUrl($tenant)"
```suggestion
    :src="filament()->getTenantAvatarUrl($tenant)"
    :alt="__('filament-panels::layout.avatar.alt', ['name' => filament()->getTenantName($tenant)])"
```

2024-03-30 10:47 UTC, zepfietje commented on packages/panels/resources/views/components/avatar/user.blade.php
> +    :alt="__('filament-panels::layout.avatar.alt', ['user' => filament()->getUserName($user)])"
```suggestion
    :alt="__('filament-panels::layout.avatar.alt', ['name' => filament()->getUserName($user)])"
```

2024-04-01 17:20 UTC, danharrin commented on packages/panels/resources/lang/en/layout.php
> +        'alt' => ':brand logo',
```suggestion
        'alt' => ':name logo',
```

2024-04-01 17:20 UTC, danharrin commented on packages/panels/resources/lang/nl/layout.php
> +            'alt' => ':brand logo',
```suggestion
            'alt' => ':name logo',
```

2024-04-01 17:20 UTC, danharrin commented on packages/panels/resources/views/components/logo.blade.php
> +            alt="{{ __('filament-panels::layout.logo.alt', ['brand' => $brandName]) }}"
```suggestion
            alt="{{ __('filament-panels::layout.logo.alt', ['name' => $brandName]) }}"
```

2024-04-01 17:21 UTC, merged

2024-04-01 17:21 UTC, danharrin commented
Thanks @mikeslinkman