Relation manager content tab improvements
laravel-filament/filament pull request #12128
Opened 2024-04-01 09:18 UTC by binaryfire

## Description

Adds the ability to set the form / infolist tab's position and icon when using `hasCombinedRelationManagerTabsWithContent()`. This is useful when the primary focus of the page is adding adding related records instead of editing the owner record itself. In these cases, the owner record is more like a "settings" section which should take a back set in the UI.

## Visual changes

Before:
![image](https://github.com/filamentphp/filament/assets/5361908/e163c8f8-c44d-4ca3-9b50-99ee7aab2f1a)

After, with `getContentTabIcon()` and `getContentTabPosition()` set in the page class:
![image](https://github.com/filamentphp/filament/assets/5361908/a75118dd-750b-40d9-b7db-72df51e39f82)

2024-04-01 18:33 UTC, danharrin requested changes

2024-04-01 18:33 UTC, danharrin commented on packages/panels/resources/views/components/resources/relation-managers.blade.php
> +                        \Filament\Support\Enums\ContentPosition::After => $tabs = $tabs + ["" => null],
Can this be done with `array_merge()`, is the result the same? That would be consistent. Also with a `null` array key instead of an empty string?

2024-04-01 18:33 UTC, danharrin commented on packages/support/src/Enums/ContentPosition.php
Please move this to `Filament\Resources\Pages` and rename to `ContentTabPosition`

2024-04-01 18:33 UTC, danharrin commented on packages/panels/docs/03-resources/07-relation-managers.md
> +## Setting an icon for the form tab
```suggestion
### Setting an icon for the form tab
```

2024-04-01 18:33 UTC, danharrin commented on packages/panels/docs/03-resources/07-relation-managers.md
> +## Setting the position of the form tab
```suggestion
### Setting the position of the form tab
```

2024-04-01 18:33 UTC, danharrin commented on packages/panels/docs/03-resources/07-relation-managers.md
> +By default, the form tab is rendered on the left. To render it on the right, you can override the `getContentTabPosition()` method on the Edit or View page class:
```suggestion
By default, the form tab is rendered before the relation tabs. To render it after, you can override the `getContentTabPosition()` method on the Edit or View page class:
```

2024-04-01 20:13 UTC, binaryfire commented on packages/support/src/Enums/ContentPosition.php
@danharrin Do you mean `Filament\Resources\Pages\Enums`? There's no `Enums` dir under `Resources\Pages` atm

2024-04-01 21:03 UTC, danharrin commented on packages/support/src/Enums/ContentPosition.php
I mean what I wrote

2024-04-01 21:16 UTC, binaryfire commented on packages/support/src/Enums/ContentPosition.php
Ok done. Although my OCD is being triggered by having an enum outside an Enums directory.

2024-04-02 07:42 UTC, merged

2024-04-02 07:42 UTC, danharrin commented
Thanks

2024-07-20 09:22 UTC, a-tarek commented
@binaryfire :wave: 
is there a way to set the default page ? 
I am setting this up but when visiting the Edit post page it goes straight to the settings sub tab 

`/admin/posts/1/edit`

is there a way to set the default page to 
`/admin/posts/1/edit/activeRelationManager=0`  ?


```php
public static function getPages(): array
{
  return [
      'edit' => Pages\EditPost::route('/{record}/edit')
    ];
 }
```