make sidebar sticky
laravel-filament/filament pull request #12456
Opened 2024-04-23 11:28 UTC by timrspratt

When using certain field components that have <template> tags in for modals and alpine collapse functionality, the sidebar can end up scrolling incorrectly over the sticky header.

The header is `sticky` with a `z-20`, so this PR adds the same to the sidebar.

Top header wrapper:
<img width="403" alt="Screenshot 2024-04-23 at 12 25 58" src="https://github.com/filamentphp/filament/assets/20431294/9e5db8aa-5f63-4d04-bd4e-ab79d6862831">

Sidebar wrapper before:
<img width="302" alt="image" src="https://github.com/filamentphp/filament/assets/20431294/dd44a943-783b-4135-b7fd-b8fa58b101e3">

Sidebar wrapper after:
<img width="344" alt="image" src="https://github.com/filamentphp/filament/assets/20431294/af708b90-3c39-4ef9-9f79-0acae8dfcf52">

Video showing issue:

https://github.com/filamentphp/filament/assets/20431294/5da54f86-a5fc-4143-a755-f7dfee818192

I have checked scenarios for mobile menu, top navigation, collapse navigation and all appear to be correct.

2024-04-24 08:07 UTC, zepfietje requested changes
Thanks for the PR, @timrspratt!

I think position `fixed` should be used instead, since the sticky position in this case would never act as relative since it's always at the top 0 already, right?

Also, could you please check if the collapsible sidebar animation on desktop still works as expected? Please post a screen recording of that here.

2024-04-24 10:53 UTC, timrspratt commented
I'll have a play with `fixed` properly when I can. A quick try just now and it looks like `w-full` would also be needed.

2024-05-06 15:02 UTC, zepfietje commented
Are you able to pick this up again, @timrspratt?

2024-05-21 06:42 UTC, zepfietje commented
I'm going to close this PR, since there hasn't been any activity and requires some more testing before it can be merged.

Feel free to open a new PR when you've had a chance to look at my change request, @timrspratt. 🙂

2024-05-21 06:42 UTC, closed without merging