Add option to remove topbar from the profile page
laravel-filament/filament pull request #12515
Opened 2024-04-26 21:30 UTC by saade

2024-04-28 07:10 UTC, danharrin commented on packages/panels/src/Pages/Auth/EditProfile.php
Please extract a trait to use here and SimplePage, probably HasTopbar

2024-04-28 07:10 UTC, danharrin requested changes
As above

2024-04-28 21:49 UTC, saade commented
@danharrin Done. Took a step further and extracted `$hasMaxWidth` too. Feel free to revert it.

2024-04-29 07:48 UTC, merged

2024-04-29 07:48 UTC, danharrin commented
Thanks!