Add support for custom plugins in Chart
laravel-filament/filament pull request #12567
Opened 2024-05-01 11:46 UTC by malzariey

## Description

This PR introduces a change in the chart.js where custom plugins can now be integrated. The creation of a new chart now includes an integration of custom plugins if they exist, enhancing the flexibility and customizability of the chart component.

## Visual changes

None

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-05-01 11:52 UTC, danharrin requested changes

2024-05-01 11:52 UTC, danharrin commented on packages/widgets/resources/js/components/chart.js
Can we refactor this somehow to get rid of the one-time variable?

2024-05-01 11:52 UTC, danharrin commented on packages/widgets/docs/03-charts.md
Please use `kebab-case` instead of `snake_case` for file names

2024-05-01 12:00 UTC, malzariey commented on packages/widgets/resources/js/components/chart.js
Completed.

2024-05-01 12:00 UTC, malzariey commented on packages/widgets/docs/03-charts.md
Completed

2024-05-03 11:52 UTC, merged

2024-05-03 11:52 UTC, danharrin commented
Thanks