Feat: Extra field wrapper attributes
laravel-filament/filament pull request #12782
Opened 2024-05-14 14:00 UTC by atmonshi

New Method: `extraFieldWrapperAttributes`, for more fields customization without the need for publishing the views.

## Description

the new method `extraFieldWrapperAttributes` will allow to add classes to the`field-wrapper`. my use case it to highlight some fields by custom CSS.

all other `extra*Attributes` will only applies to the input itself

## Visual changes:

Screenshots:
- with `extra*Attributes`:
![Screenshot_2024-05-13_110915](https://github.com/filamentphp/filament/assets/1952412/27c9d2ff-4398-4b43-a263-0726d2edba1d)

- with extraFieldWrapperAttributes:
![Screenshot_2024-05-13_105903](https://github.com/filamentphp/filament/assets/1952412/ee3a8461-3da0-4691-889c-0a4d0091d0a0)

## Usage:
```php
TextInput::make('name')
    ->extraFieldWrapperAttributes(['class' => 'components-locked'])
```

## Functional changes

- [ ] Code style has been fixed by running the `composer cs` command.
- [ ] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

2024-05-15 08:08 UTC, danharrin requested changes

2024-05-15 08:08 UTC, danharrin commented on packages/forms/resources/views/components/radio.blade.php
You don't need to pass extraFieldWrapperAttributes into every view like that, in the field wrapper you can call `$field->getExtraFieldWrapperAttributes()` like all the other properties like the label. That should make this PR much much smaller

2024-05-15 10:48 UTC, atmonshi commented on packages/forms/resources/views/components/radio.blade.php
ooh, how I didn't notice all that!!
sorry 😅 reverted and refactored

2024-05-15 11:54 UTC, danharrin requested changes
Please do the same for the infolist entry wrapper, and remove the changes to composer.lock

2024-05-15 12:29 UTC, atmonshi commented
> Please do the same for the infolist entry wrapper, and remove the changes to composer.lock

all done 👍, and revert composer.lock

2024-05-16 10:38 UTC, danharrin commented on packages/infolists/docs/03-entries/01-getting-started.md
> +Passing extra HTML attributes to the entry wrapper:
```suggestion
You can also pass extra HTML attributes to the entry wrapper which surrounds the label, entry, and any other text:
```

2024-05-16 10:38 UTC, danharrin commented on packages/forms/docs/03-fields/01-getting-started.md
> +Passing extra HTML attributes to the field wrapper:
```suggestion
You can also pass extra HTML attributes to the field wrapper which surrounds the label, entry, and any other text:
```

2024-05-16 10:49 UTC, merged

2024-05-16 10:50 UTC, danharrin commented
Thanks!