feat: add support to override media model on spatie media file upload
laravel-filament/filament pull request #12829
Opened 2024-05-16 15:47 UTC by WayneHarris

## Description

Adding support to override the media model on SpatieMediaLibraryFileUpload in line with the ability to do so in the Spatie Media Libday since version [11.4.0](https://github.com/spatie/laravel-medialibrary/releases/tag/11.4.0)

## Visual changes

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [ ] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

2024-05-16 15:49 UTC, WayneHarris commented
@danharrin, What are your thoughts on this? I can test and review further if you think it is worthwhile.

2024-05-17 09:08 UTC, danharrin requested changes
I think the part that reads `getMediaModel()` from the record is fine, but I don't understand the need for the new property and methods to set a component-specific media class? Especially when it's only used within the method that reorders files, not anywhere else? I think this could be greatly simplified to support the new method on the model?

2024-05-17 09:22 UTC, WayneHarris commented
> I think the part that reads `getMediaModel()` from the record is fine, but I don't understand the need for the new property and methods to set a component-specific media class? Especially when it's only used within the method that reorders files, not anywhere else? I think this could be greatly simplified to support the new method on the model?

Agree, I did wonder on this too, I'll confirm it's redundant and remove it.

2024-05-17 12:10 UTC, danharrin commented
Thank you

2024-05-17 12:11 UTC, merged