Button with custom size: fix Attempt to read property "value" on string
laravel-filament/filament pull request #13038
Opened 2024-05-31 15:55 UTC by underdpt

## Description

When using button component with custom size an exception is thrown:

```php
<x-filament::button
    size="gap-1.5 px-4 py-3 text-xl"
>
    New
</x-filament::button>
```

## Visual changes

Nothing

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-06-01 06:46 UTC, zepfietje requested changes

2024-06-01 06:46 UTC, zepfietje commented on packages/support/resources/views/components/button/index.blade.php
> +            "fi-size-{$sizeClassSuffix}" => $size instanceof ActionSize,
Could you update the PR to just use the value inline? No need to have the array value as condition if we already conditionally return the string or null.

2024-06-01 06:49 UTC, zepfietje commented
Could you apply this change to all other components that need it, @underdpt? Link, icon button, badge, etc.

2024-06-04 08:29 UTC, underdpt commented
Hi, 

It seems only link is affected, i've made the requested changes and applied them to the link component.

Thanks

2024-06-04 09:46 UTC, zepfietje requested changes

2024-06-04 09:46 UTC, zepfietje commented on packages/support/resources/views/components/button/index.blade.php
> +            $sizeClassSuffix ? "fi-size-{$sizeClassSuffix}" : null,
```suggestion
            ($size instanceof ActionSize) ? "fi-size-{$size->value}" : null,
```

2024-06-04 09:56 UTC, underdpt commented on packages/support/resources/views/components/button/index.blade.php
> +            $sizeClassSuffix ? "fi-size-{$sizeClassSuffix}" : null,
Done. 

Long day, sorry

2024-06-04 10:08 UTC, zepfietje approved these changes
Thanks!

2024-06-04 10:08 UTC, merged