Fix: Prevent infolist entry grid blowout
laravel-filament/filament pull request #13125
Opened 2024-06-06 17:18 UTC by ralphjsmit

## Description

I have an a custom infolist component. The contents of this custom component are sometimes wider than the actual space allowed in the infolist grid layout. This is handled in the custom component by setting an `overflow-x-scroll`. 

However, this overflow class isn't applied om the infolist, because the infolist entry wrapper grid gives the children automatically a width of `auto`, meaning that because the infolist entry wrapper has this grid, all the children are [automatically given as much width as they can occupy](https://css-tricks.com/preventing-a-grid-blowout/), without giving the developer an option to use a scroll overflow for example.

I tested by and this doesn't change any behaviour for existing custom components that are overflow, only for components that have an `overflow-...` property set.

Thanks!

## Visual changes

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-06-08 09:47 UTC, zepfietje requested changes

2024-06-08 09:47 UTC, zepfietje commented on packages/infolists/resources/views/components/entry-wrapper/index.blade.php
> +                    'min-w-0',
Wouldn't `grid-cols-1` be a slightly cleaner fix in this case?
It's the equivalent of `grid-template-columns: repeat(1, minmax(0, 1fr));`, which fixes the overflow issue at the grid level (as explained in the article you linked to).

2024-06-08 11:38 UTC, zepfietje commented on packages/infolists/resources/views/components/entry-wrapper/index.blade.php
> +                    'min-w-0',
Tested and achieves the same result.

2024-06-08 12:10 UTC, zepfietje approved these changes

2024-06-08 12:10 UTC, merged

2024-06-08 12:10 UTC, zepfietje commented
Thanks for bringing this up and referencing that article, @ralphjsmit!

2024-06-08 16:54 UTC, ralphjsmit commented
Thank you for the thorough review! Yeah, I agree the grid-template-columns solution is better to do it on the grid level. I can work well with Tailwind, but my main focus is now on PHP/backend, so I don't know all these CSS intricacies 😄 Good weekend!

2024-06-09 12:00 UTC, zepfietje commented
No worries, Ralph! It's all a team effort. Enjoy your Sunday. 😊