feature: add empty state to chart widgets
laravel-filament/filament pull request #13408
Opened 2024-06-26 21:45 UTC by juliangums

## Description
> [!CAUTION]
> DON'T MERGE THIS YET!

@danharrin as discussed in https://github.com/filamentphp/filament/discussions/13311 I have added a feature to display an empty state on chart widgets. Before this is merged, I'd like to ask a couple of things as I am not entirely familiar with everything in Filament:
1) I added a string and translations for `en` and `de`. Is that enough? How are all the other translations handled for so many languages?
2) I didn’t use screenshots or links in the docs as I didn’t know how to do them.
3) The implementation is very much based on the work done on tables. But as we aren't defining these things by calling methods on an object but rather by defining a class that extends ChartWidget, I removed all the setters from it. But I guess that also means closures don't really make sense for the attributes or do they? I want to make sure this is in the spirit of Filament so any guidance would be much appreciated.
4) Is everything else as you'd expect? Anything I missed?

Let me know and I'll get the rest sorted.
Otherwise, it's ready to be tested.

## Visual changes
<img width="616" alt="Screenshot 2024-06-26 at 23 22 49" src="https://github.com/filamentphp/filament/assets/22907521/b9c24816-c91b-4cea-8bdc-771ab9f279a6">

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-06-27 06:40 UTC, zepfietje requested changes
Thanks for this PR, @juliangums!

I don't like the duplication of empty state Blade views.
Since I was already planning to extract the empty state component from tables, shall we get https://github.com/filamentphp/filament/issues/13252 done before merging your new feature?

2024-06-27 07:32 UTC, juliangums commented
@zepfietje that would make a ton of sense. Let me know when that’s done or if you need any help just instruct me.

2024-06-27 07:55 UTC, zepfietje commented
Great! It's at the top of my list, so will get to it as soon as possible.

I'll mark this PR as draft until we can move forward. 👍

2024-07-19 08:55 UTC, zepfietje commented
Started working on https://github.com/filamentphp/filament/pull/13642.

2025-01-30 11:24 UTC, danharrin commented
Going to close this since there was no movement on #13642. Next step would be putting in a v4 PR for an empty state Blade component, and then opening another PR to add that to the chart widget.

2025-01-30 11:24 UTC, closed without merging

2025-01-30 15:51 UTC, lambda-bajara commented
@juliangums  @zepfietje So this was not deployed? Is it only going to be launched in v4?
Just to make sure... I'm needing this 😅