Show bulk actions below table
laravel-filament/filament pull request #13530
Opened 2024-07-10 12:40 UTC by howdu

## Description
Add option to display bulk actions below table

```php
->bulkActions([
])
->bulkActionsPosition(Tables\Enums\BulkActionsPosition::BelowTable)
```

## Visual changes
<img width="852" alt="Screenshot 2024-07-10 at 13 38 58" src="https://github.com/filamentphp/filament/assets/533658/ba770d85-db58-4478-92a7-b7d3e5db7223">

<img width="1226" alt="Screenshot 2024-07-10 at 13 35 58" src="https://github.com/filamentphp/filament/assets/533658/a4c3d71c-a57a-476f-8ac4-1cbcf69a38a6">

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-07-15 14:46 UTC, danharrin commented
@zepfietje would appreciate the green light on the design before I proceed into the code please

2024-07-19 07:39 UTC, zepfietje commented
Personally I don't think having the actions at the bottom results in a good UI/UX.
Could you clarify your reasoning here, @howdu?

2024-07-19 07:54 UTC, howdu commented
@zepfietje it was a client who requested it - their reasoning was they work their way down the table selecting all the relevant records and always finish at the bottom where they wanted the action button instead of having to scroll to the top.

The table is implemented as a checklist where they need to work through all the rows selecting all the relevant records at once.

2024-07-19 08:03 UTC, zepfietje commented
Hmm, I'm wondering if the bulk select checkbox and select/deselect actions should be in the footer too then?

2024-07-21 07:03 UTC, howdu commented
@zepfietje I've added this above the action let me know what you think.
<img width="386" alt="Screenshot 2024-07-21 at 07 45 37" src="https://github.com/user-attachments/assets/b945488f-266c-42fd-9ce3-9cb0fc1f45ab">

<img width="761" alt="Screenshot 2024-07-21 at 07 45 54" src="https://github.com/user-attachments/assets/eac5973e-aad9-402e-91d9-6515f3d5d58d">

Also added the option to display both above and below table. You can get clever with not displaying this on a small tables.
```php
->bulkActionsPosition(
    fn (Table $table) => $table->getRecords()->count() > 5
        ? Tables\Enums\BulkActionsPosition::AboveAndBelowTable
        : Tables\Enums\BulkActionsPosition::AboveTable
)
```

2024-07-25 09:13 UTC, zepfietje requested changes

2024-07-25 09:13 UTC, zepfietje commented on packages/tables/resources/views/index.blade.php
> +            <div
Is there a way to minimize duplication here and in the header?
Maintenance of the table index view is already very hard, so I don't want to introduce additional complexity.

2024-07-25 09:14 UTC, zepfietje commented
@howdu, shouldn't it also show the bulk selection checkbox?
It should be identical to what's in the header, right?

2024-07-28 12:47 UTC, howdu commented
@zepfietje I think adding the bulk checkbox would overcomplicating this. I was trying to keep it simple and work the same as filter position above/below.

2024-08-06 07:07 UTC, zepfietje commented
Alright, I understand now since the bulk selection checkbox is in the column headers row.
What does this PR look like when positioning bulk actions *and* filters in the footer of the table, @howdu?

2024-08-09 13:07 UTC, howdu commented
@zepfietje it displays above the pagination so doesn't affect that. 

<img width="868" alt="Screenshot 2024-08-09 at 14 03 39" src="https://github.com/user-attachments/assets/0576f4bc-cdb9-4353-bebd-4af5212cdd95">

<img width="339" alt="Screenshot 2024-08-09 at 14 04 43" src="https://github.com/user-attachments/assets/94a0739a-af0f-4d82-827b-e688c4e24d32">

2024-08-12 13:01 UTC, howdu commented on packages/tables/resources/views/index.blade.php
> +            <div
@zepfietje please let me know what changes you think best to improve this. 

Perhaps using `capture` blade directive? But due to it not including the reorder action in the footer I think the `selection-indicator` and bulk action`filament-tables::actions` would need to be captured separately?

2025-01-30 11:25 UTC, danharrin commented
Going to close this as it feels stale. I'm not entirely sure I like how the bulk actions look under the table and I can't say I've had many requests for it either. If there is a particular explanation behind it, let me know and we can consider accepting a PR in v4.

2025-01-30 11:25 UTC, closed without merging