Make Select relationship() consider HasOne and HasMany relationships
laravel-filament/filament pull request #13542
Opened 2024-07-11 22:53 UTC by smpita

## Description

When using a `Filament\Forms\Components\Select` on a `HasOne` or `HasMany` relationship, a `BelongsTo` is assumed by the line `/** @var BelongsTo $relationship */`

When a related model is found `$relationship->getOwnerKeyName()` gets called resulting in a runtime failure due to `getOwnerKeyName` not being a valid function on `HasOne` or `HasMany`

## Visual changes

No visual differences

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-07-15 15:06 UTC, danharrin requested changes

2024-07-15 15:06 UTC, danharrin commented on packages/forms/src/Components/Select.php
> +                        $relatedModel->getKeyName(),
I think you need the get the key name from the relationship in case it was customised?

2024-07-15 15:06 UTC, danharrin commented on packages/forms/src/Components/Select.php
> +                        $relatedModel->getKeyName(),
Also what happens if this is a HasMany instead of a HasOne? Then you need to pluck from a collection I think

2024-07-18 22:57 UTC, smpita commented on packages/forms/src/Components/Select.php
> +                        $relatedModel->getKeyName(),
Good catches.
I also missed the early return after setting the state.

2024-07-24 10:40 UTC, danharrin requested changes

2024-07-24 10:40 UTC, danharrin commented on packages/forms/src/Components/Select.php
> +                        $relationship->getForeignKeyName()
```suggestion
                        $relationship->getForeignKeyName(),
```

2024-07-24 10:40 UTC, merged

2024-07-24 10:40 UTC, danharrin commented
Thank you