Allow table groups to accept a closure
laravel-filament/filament pull request #13559
Opened 2024-07-13 01:13 UTC by archilex

## Description

Allow table groups to accept a closure:

```php
return $table
    ->groups(function (Component $livewire) {
        return match ($livewire->activeTab) {
            'pending' => ['order_date'],
            'shipped' => ['shipping_date'],
            'delivered' => ['delivered_date'],
        };
    })
```

## Visual changes

## Functional changes

- [X] Code style has been fixed by running the `composer cs` command.
- [X] Changes have been tested to not break existing functionality.
- [X] Documentation is up-to-date.

2024-07-15 15:13 UTC, danharrin requested changes

2024-07-15 15:13 UTC, danharrin commented on packages/tables/src/Table/Concerns/CanGroupRecords.php
Before, multiple calls to `getGroups()` would not need to reconstruct the array of ID-keyed groups. Now, that happens.

Please introduce a new `cachedGroups` property where you save the keyed groups into, so that doesn't run multiple times.

Please also fix the `@var` docblock on the `$groups` property and argument to introduce the closure and string value and remove the string key.

2024-07-15 16:18 UTC, archilex commented on packages/tables/src/Table/Concerns/CanGroupRecords.php
@danharrin Good call. Added the `cachedGroups` property and also added a `getCachedGroups()` method to be consistent with the rest of the code base.

2024-07-16 07:39 UTC, danharrin commented on packages/tables/src/Table/Concerns/CanGroupRecords.php
I think in this case, we can avoid the new method and implement this within `getGroups()` please, I usually add the extra method if the original method is overridable by the user which would break the caching

2024-07-16 13:20 UTC, archilex commented on packages/tables/src/Table/Concerns/CanGroupRecords.php
Sounds good! Done.

2024-07-17 09:54 UTC, merged

2024-07-17 09:54 UTC, danharrin commented
Thanks!