Fix: avoid table polling while reordering
laravel-filament/filament pull request #13593
Opened 2024-07-16 11:14 UTC by smiliyas

## Description

closes #12108 

## Visual changes

NA

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

2024-07-17 10:13 UTC, danharrin requested changes

2024-07-17 10:13 UTC, danharrin commented on packages/tables/resources/views/index.blade.php
> +            @if (! $isReordering && ($pollingInterval = $getPollingInterval()))
```suggestion
            @if ((! $isReordering) && ($pollingInterval = $getPollingInterval()))
```

2024-07-17 10:15 UTC, merged

2024-09-16 09:44 UTC, kaspernowak commented
Thanks @smiliyas for this fix!
I do see an issue with this though "blanket" solution though, as it will stop all polling when reordering is enabled, instead of just when a record is actively being dragged. A better approach IMO would be to set a parameter to true when the sortablejs onStart event is triggered and set to false when the onEnd event is triggered. 
This fix effectively forces me to remove the reordering functionality from my table, as polling is essential for me when I work with my orders table and doing delivery routing in rush hour, as I would not see new orders when reordering records.

@danharrin Is it feasible to tap into the sortablejs onStart and onEnd events here?

2024-09-16 09:46 UTC, danharrin commented
You will have to test it yourself, I don't know if removing the attribute from JS would be enough in case an additional Livewire render happens while dragging

2024-09-16 10:19 UTC, kaspernowak commented
@danharrin Maybe there could be a quick fix to this. Is there a way to manually trigger a table polling/refresh/update event in a `ListRecords` component method? Like as we can do `$this->getTableRecords()`, can we do something like `$this->pollTable()`?

2024-09-16 10:31 UTC, danharrin commented
From JavaScript or PHP?

2024-09-16 10:33 UTC, kaspernowak commented
from PHP in an overwritten `reorderTable` method.

2024-09-16 10:34 UTC, danharrin commented
It happens every time Livewire renders anyway

2024-09-16 10:38 UTC, kaspernowak commented
@danharrin Whenever I reorder my records, I trigger actions that update related records. The updated values of the related records do not show before I refresh the page (or disable reordering). So I want to force this update at the end of my reordering actions, is there a way to do this?

2024-09-16 10:48 UTC, danharrin commented
That is a Livewire method, so after dropping the page should rerender and you should see updates.

2024-10-07 10:42 UTC, kaspernowak commented
It turned out to be an issue with how I pulled the table records with `$this->getTableRecords()` in my overwritten method. defining a public parameter for `$tableRecords´ on my List page for the table records, pulling the table records in my getHeaderWidgets method with `$this->getTableRecords()` and storing it in the public parameter instead, and using `$tableRecords´ in my overwritten method did not result in failed table record updates on reordering. I don't fully understand livewire and how table records are handled on filament pages, but it seems like it works for now. Sorry for the off topic, just wanted to conclude this.