4.x Add Trix Toolbar Button Subscript & Superscript
laravel-filament/filament pull request #14185
Opened 2024-09-09 07:30 UTC by untillnesss

## Description
Here I added a new button to the Trix Toolbar, which functions to create Subscript and Superscript for a pleasant mathematical formula writing experience.

## Visual changes
Before
![image](https://github.com/user-attachments/assets/2bccfc66-5405-406d-86e2-6f96ec413a41)

After
![image](https://github.com/user-attachments/assets/0df3a1b3-80c5-4936-ab62-f2a44462cab3)

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-12-02 15:54 UTC, danharrin requested changes

2024-12-02 15:54 UTC, danharrin commented on packages/forms/resources/lang/en/components.php
Please ensure these are added in alphabetical order here

2024-12-02 15:54 UTC, danharrin commented on packages/forms/docs/02-fields/10-rich-editor.md
Please add these in alphabetical order

2024-12-11 12:46 UTC, untillnesss commented on packages/forms/resources/lang/en/components.php
Done

2024-12-11 12:46 UTC, untillnesss commented on packages/forms/docs/02-fields/10-rich-editor.md
Done

2025-02-02 20:07 UTC, merged

2025-02-02 20:07 UTC, danharrin commented
Thanks