Feature: XLSX Writer Options
laravel-filament/filament pull request #14411
Opened 2024-10-01 18:21 UTC by mmonari

## Description

This PR adds a `getXlsxOptions()` method to the Exporter class to allow users to further customize their exported XLSX documents, such as column widths, or any other `OpenSpout\Writer\XLSX` options  as documented at the [OpenSpout Documentation](https://github.com/openspout/openspout/blob/4.x/docs/documentation.md)

## Code style
- [x] Code style has been fixed by running the `composer cs` command.

## Testing
- [x] Changes have been tested to not break existing functionality.

## Documentation
- [ ] Documentation is up-to-date.

### Note:
As this is my first PR, I appreciate your understanding regarding my commit history. The first one represents the actual changes, the second was after executing a `composer cs`  and it should have been described differently.

2024-10-02 15:52 UTC, mmonari commented
Ping @danharrin

2024-10-07 12:41 UTC, danharrin requested changes

2024-10-07 12:41 UTC, danharrin commented on packages/actions/src/Exports/Exporter.php
> +    public function getXlsxOptions(): ?Options
```suggestion
    public function getXlsxWriterOptions(): ?Options
```

2024-10-07 12:41 UTC, danharrin commented on packages/actions/src/Exports/Jobs/CreateXlsxFile.php
> +        $writer = app(Writer::class, ['options' => $this->exporter->getXlsxOptions() ?? null]);
```suggestion
        $writer = app(Writer::class, ['options' => $this->exporter->getXlsxWriterOptions()]);
```

2024-10-07 12:56 UTC, merged