Make filterMediaUsing() available in SpatieMediaLibraryImageColumn and SpatieMediaLibraryImageEntry
laravel-filament/filament pull request #14593
Opened 2024-10-21 23:54 UTC by NBZ4live

## Description

Adds media filters (previously available only in SpatieMediaLibraryFileUpload) to SpatieMediaLibraryImageColumn and SpatieMediaLibraryImageEntry. Moves the related methods to a concern.

## Visual changes

No changes

## Functional changes

- [ ] Code style has been fixed by running the `composer cs` command.
- [ ] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

2024-10-22 09:10 UTC, danharrin requested changes

2024-10-22 09:10 UTC, danharrin commented on packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
> +
Is this required if it's also in the trait?

2024-10-22 09:10 UTC, danharrin commented on packages/spatie-laravel-media-library-plugin/src/Resources/Concerns/HasMediaFilter.php
Please move this trait to `src/Support/Concerns`

2024-10-22 10:17 UTC, NBZ4live commented
Pushed the fixes

2024-10-23 06:53 UTC, merged

2024-10-23 06:53 UTC, danharrin commented
Thanks