Add console command optimization in FilamentServiceProvider
laravel-filament/filament pull request #14601
Opened 2024-10-23 11:49 UTC by damms005

Sponsored by a relatively new addition to the Laravel framework: https://laravel.com/docs/11.x/packages#optimize-commands.

This will be helpful in local dev, especially whne clearing the cache and forgetting to clear Filament's cache.

2024-10-24 08:16 UTC, danharrin requested changes

2024-10-24 08:16 UTC, danharrin commented on packages/panels/src/FilamentServiceProvider.php
> +                $this->optimizes(
Did you test this? I think the method name in the check is wrong.

2024-10-24 13:43 UTC, merged

2024-10-27 10:44 UTC, zepfietje commented
@danharrin shouldn't this be in the support package's `SupportServiceProvider.php` file?

2024-10-27 12:16 UTC, danharrin commented
Yeah good catch, fixed

2024-10-27 14:12 UTC, zepfietje commented
Great, thanks for fixing! 🫶