Adds missing translations + refactor language files for clarity, consistency, and grammatical accuracy
laravel-filament/filament pull request #14641
Opened 2024-10-27 18:06 UTC by deusmar

- Simplification and Reduction of Redundancy;
- Adjustment for Grammatical Agreement and Textual Cohesion
- Standardization of Terms
- Adjustment of Verb-Preposition Usage
- Adaptation to User Expectations and Digital Context

2024-10-28 13:08 UTC, saade approved these changes

2024-10-28 17:59 UTC, leandrocfe requested changes
@deusmar, thank you for the PR. Could you check the comments please?

2024-10-28 17:59 UTC, leandrocfe commented on packages/panels/resources/lang/pt_BR/layout.php
Filament uses _Login_ and _Logout_ even in Portuguese. While these terms aren't translated, they are widely recognized and commonly used in Portuguese to describe these actions across many applications.
I prefer it in English, but I'm open to translating it. If we do translate, though, we should also apply the same approach to the word _Login_.

2024-10-28 17:59 UTC, leandrocfe commented on packages/panels/resources/lang/pt_BR/unsaved-changes-alert.php
Ok

2024-10-28 17:59 UTC, leandrocfe commented on packages/actions/resources/lang/pt_BR/import.php
Ok

2024-10-28 17:59 UTC, leandrocfe commented on packages/actions/resources/lang/pt_PT/import.php
This is actually in pt_PT, and no changes are needed here.

2024-10-28 17:59 UTC, leandrocfe commented on packages/forms/resources/lang/pt_BR/components.php
You mentioned some changes, such as "Adicionar em" to "Adicionar a", "Recolher todos" to "Recolher tudo", etc. Although both seem grammatically correct, I think if we decide to make these adjustments, we should apply them consistently across other areas, such as in the Repeater component. For instance, Repeater uses labels like Builder, and it would feel inconsistent if we update labels in Builder but not in Repeater..

2024-11-08 08:09 UTC, danharrin commented
@deusmar please check @leandrocfe's review, we cannot merge this without the comments being addressed

2024-11-11 17:25 UTC, deusmar commented
Sorry guys, let me check them. Thanks for the heads-up.

2024-11-24 17:03 UTC, danharrin commented
Please reopen this when those changes have been addressed. Thanks.

2024-11-24 17:03 UTC, closed without merging