Added sample generated image
laravel-filament/filament pull request #14962
Opened 2024-12-02 07:55 UTC by ModestasV

## Description

With this PR, I am checking for the need to improve documentation. In this specific example, there will be an image added to:

Panels -> Navigation -> Customizing the user menu

This example adds one image but should become a starting point for generating more images. In other words - I would love some feedback if we figured out the workflow correctly and if we should continue adding them :)

## Visual changes

No changes to the Filament Application.

Change only affects documentation (I did not find a way to build it locally to add screenshots, sorry!)

## Functional changes

- [ ] Code style has been fixed by running the `composer cs` command.
- [ ] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-12-02 10:31 UTC, danharrin requested changes

2024-12-02 10:31 UTC, danharrin commented on docs-assets/screenshots/schema.js
> +            await page.click('body > div.fi-layout.flex.min-h-screen.w-full.flex-row-reverse.overflow-x-clip > div.fi-main-ctn.w-screen.flex-1.flex-col.opacity-0 > div > nav > div > div > div.fi-drop
I really REALLY appreciate the work you put into this, adding screenshots to the docs is a goal we have and it's great to see people investigate the screenshot system we have in order to contribute, as it scares a lot of people off

My only feedback here is to suggest that we add CSS classes to Filament so these selectors can be simplified, I don't want them to break if we change Tailwind classes etc.

2024-12-02 11:27 UTC, ModestasV commented on docs-assets/screenshots/schema.js
> +            await page.click('body > div.fi-layout.flex.min-h-screen.w-full.flex-row-reverse.overflow-x-clip > div.fi-main-ctn.w-screen.flex-1.flex-col.opacity-0 > div > nav > div > div > div.fi-drop
Not going to lie - it was a bit scary to use it! But now, it is pretty obvious.

My question unrelated to this - is there a way to generate a preview with documentation? Would love to be sure it was actually added :)

As for a custom class - will see what I can do and update it accordingly, thanks for feedback!

2024-12-02 11:40 UTC, danharrin commented on docs-assets/screenshots/schema.js
> +            await page.click('body > div.fi-layout.flex.min-h-screen.w-full.flex-row-reverse.overflow-x-clip > div.fi-main-ctn.w-screen.flex-1.flex-col.opacity-0 > div > nav > div > div > div.fi-drop
Once the PR is merged, the image will be hosted on GitHub & then you can run `npm run generate-docs` from the `filamentphp.com` repo to check it out, but I will do that for you when I deploy next

2024-12-02 16:25 UTC, ModestasV commented on docs-assets/screenshots/schema.js
> +            await page.click('body > div.fi-layout.flex.min-h-screen.w-full.flex-row-reverse.overflow-x-clip > div.fi-main-ctn.w-screen.flex-1.flex-col.opacity-0 > div > nav > div > div > div.fi-drop
I changed the selector path to simplify it (avoiding copying from the browser).

I think this is a reasonable approach since just a few components are visible anyway.

2024-12-02 16:36 UTC, danharrin requested changes
Can you try and work out a way to add some space around the outside of the screenshots please? Essentially zoom out so you can see some of the elements around the outside of the dropdown, so it looks more natural. Have a look at the other screenshots for inspiration maybe

2024-12-02 16:38 UTC, ModestasV commented
Will see what's possible :)

2024-12-02 17:52 UTC, danharrin approved these changes
This looks great, thanks!

2024-12-04 13:25 UTC, danharrin requested changes

2024-12-04 13:25 UTC, danharrin commented on docs-assets/screenshots/schema.js
> +        url: 'top-bar',
```suggestion
        url: 'topbar',
```

2024-12-04 13:25 UTC, danharrin commented on docs-assets/app/routes/web.php
> +Route::get('/top-bar', Topbar::class);
```suggestion
Route::get('/topbar', Topbar::class);
```

2024-12-04 13:25 UTC, danharrin commented on docs-assets/app/app/Livewire/Topbar.php
> +                    ->url(fn(): string => '#topbar-link-example')
```suggestion
                    ->url(fn (): string => '#')
```

2024-12-04 13:28 UTC, merged

2024-12-04 13:28 UTC, danharrin commented
Thanks!

2024-12-04 13:30 UTC, ModestasV commented
Oh, you accepted this 😅 Will be adding more images (practically all of them to the Navigation section) with next PR then :)

2024-12-04 13:44 UTC, danharrin commented
Thanks! I have deployed the first screenshot to the website

2024-12-04 14:36 UTC, ModestasV commented
Hmm, it doesn't seem to have loaded... Did I make a mistake anywhere? Or is there some delay?

2024-12-04 15:19 UTC, danharrin commented
For some reason Forge didn't pick up the deployment, but I've done it again