Add labels for create and edit option actions  in Select input to show label on sr-only for current local.
laravel-filament/filament pull request #14978
Opened 2024-12-02 18:43 UTC by A909M

## Description

I just add label on createOption and editOption Actions to show icon button label on sr-only for current local.

## Visual changes

### **Before**
English en
![145](https://github.com/user-attachments/assets/5724e9d5-4e1e-458f-82b0-d20467a78014)

 Arabic ar
![ar_before](https://github.com/user-attachments/assets/f16c0964-c299-4e58-8a00-5530fd806143)

### After

English en
![en_after](https://github.com/user-attachments/assets/fd6a8f57-c977-4246-ae13-ece9be12f267)

Arabic ar
![create_ar_after](https://github.com/user-attachments/assets/5626a0f3-92b2-465f-8ba7-6aec5cf8ee3a)
![edit_ar_after](https://github.com/user-attachments/assets/b21f3c96-e4a9-45eb-92eb-e749fca75db8)

## Functional changes

- [ ] Code style has been fixed by running the `composer cs` command.
- [ ] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

2024-12-03 09:21 UTC, danharrin requested changes
Please introduce new `create_option.label` and `edit_option.label` keys in the translation files for this. We never reuse strings as a principle, the modal heading might need to be longer than the label for example.

2024-12-03 15:38 UTC, A909M commented
> Please introduce new `create_option.label` and `edit_option.label` keys in the translation files for this. We never reuse strings as a principle, the modal heading might need to be longer than the label for example.

Thank you for your feedback. I've implemented the` create_option.label` and `edit_option.label` keys in the translation files as requested.

2024-12-04 12:20 UTC, danharrin commented
The first example looks fine thank you

2024-12-05 08:40 UTC, merged

2024-12-05 08:40 UTC, danharrin commented
Thanks

2024-12-05 19:58 UTC, A909M commented
> Thanks

You're welcome :)