Feature: Uncontained Fieldset
laravel-filament/filament pull request #14975
Opened 2024-12-02 14:56 UTC by thethunderturner

## Description

Closes #11355. This has to be discussed with @zepfietje before merging

## Visual changes

![image](https://github.com/user-attachments/assets/8f795eef-79e4-4d9f-b3ec-e5b48a8a73e1)
![image](https://github.com/user-attachments/assets/ffd1ee56-9db4-43df-b6e8-4f312d673db2)

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-12-02 15:35 UTC, danharrin commented
Please check #14968 for how I implemented it in the Section, with the `-not-` class instead, and using the `CanBeContained` trait.

2024-12-02 15:41 UTC, thethunderturner commented
> Please check #14968 for how I implemented it in the Section, with the `-not-` class instead, and using the `CanBeContained` trait.

Will do. Thanks

2024-12-02 15:43 UTC, danharrin commented
The reason I want the `-not` class is because my philosophy is that an element should have a minimal number of CSS classes to achieve the "default" look, so if someone uses the raw classes instead of the Blade component they can achieve it easier.

2024-12-02 15:56 UTC, danharrin commented on packages/support/resources/css/components/fieldset.css
I don't think this is right, the code needs to apply if there is `:not()` this class present. Can you make sure you test it locally please?

2024-12-02 15:58 UTC, danharrin requested changes
Please add more space between the legend and the content, I think it needs to at least look the same as `gap-6`

But I would like to hear what Zep's idea was for this, as I don't think I'd ever use an uncontained fieldset

2024-12-02 16:03 UTC, thethunderturner commented on packages/support/resources/css/components/fieldset.css
Yeah you're right. Im still working on it thuogh :sweat_smile:

2024-12-02 16:23 UTC, thethunderturner commented
> Please add more space between the legend and the content, I think it needs to at least look the same as `gap-6`
> 
> But I would like to hear what Zep's idea was for this, as I don't think I'd ever use an uncontained fieldset

Unfortunately `gap` wont work because we're using the `display: block` property which prevents gap from having an effect. Instead I used `padding-top` which in this case I believe has the same result.

2024-12-19 13:41 UTC, thethunderturner commented
Hey @zepfietje, is there any update on this?

2025-04-18 06:53 UTC, zepfietje commented
@thethunderturner could you share screenshots of the current state of this PR?

2025-04-18 07:12 UTC, thethunderturner commented
> @thethunderturner could you share screenshots of the current state of this PR?

Will do!

2025-06-09 08:20 UTC, danharrin approved these changes

2025-06-09 08:21 UTC, merged