Panels navigation documentation
laravel-filament/filament pull request #15109
Opened 2024-12-17 12:26 UTC by ModestasV

## Description

Documentation updates for Panels -> Navigation.

This includes a few non-documentation updates:

1. I have refactored the routes to be grouped instead of the `panels/navigation...` prefix ([Commit](https://github.com/filamentphp/filament/commit/064fdff43029399caa47c58ae53d99e53c4e8fd5#diff-76283389dc47ea1c7439220dfa1f0567f31184308ecd00d47a9ef7bd3f635f48R28))
2. Fixed a bug with the generation script where having a `Dark` preference would not generate `Light` screenshots ([Commit](https://github.com/filamentphp/filament/commit/0a08e8ee9ff088c2e5c97e278e440e9a0b0a2b6c))

And, of course, added images for:

- https://filamentphp.com/docs/3.x/panels/navigation#customizing-a-navigation-items-icon
- https://filamentphp.com/docs/3.x/panels/navigation#switching-navigation-item-icon-when-it-is-active
- https://filamentphp.com/docs/3.x/panels/navigation#sorting-navigation-items
- https://filamentphp.com/docs/3.x/panels/navigation#collapsible-sidebar-on-desktop
- https://filamentphp.com/docs/3.x/panels/navigation#registering-custom-navigation-items
- https://filamentphp.com/docs/3.x/panels/navigation#using-top-navigation
- https://filamentphp.com/docs/3.x/panels/navigation#adding-a-badge-to-a-navigation-item
- https://filamentphp.com/docs/3.x/panels/navigation#grouping-navigation-items
- https://filamentphp.com/docs/3.x/panels/navigation#making-navigation-groups-not-collapsible
- https://filamentphp.com/docs/3.x/panels/navigation#disabling-navigation

In one case, I had to split the text better to visualize the difference (Collapsible vs. not group).

Other than that - let me know if this is okay :) 

## Visual changes

None

## Functional changes

- [ ] Code style has been fixed by running the `composer cs` command.
- [ ] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-12-31 09:11 UTC, danharrin requested changes

2024-12-31 09:11 UTC, danharrin commented on packages/panels/docs/06-navigation.md
> +<AutoScreenshot name="panels/navigation/custom-items" alt="Register Custom Navigation Items" version="3.x" />
Please do not use Title Case for the alt text within screenshots, please check this is consistent with existing screenshots :)

2024-12-31 09:11 UTC, danharrin commented on docs-assets/screenshots/images/light/panels/navigation/sort-items.jpg
Maybe we could use a badge for the sort number instead of putting it in the label?

2024-12-31 09:11 UTC, danharrin commented on docs-assets/screenshots/images/light/panels/navigation/active-icon.jpg
Maybe the example here could be an `-o-` cog and a `-s-` cog?

2024-12-31 09:11 UTC, danharrin commented on docs-assets/app/routes/web.php
> +Route::group(['prefix' => 'panels'], function () {
Can we use `Route::prefix()` here please for better static analysis

2024-12-31 09:11 UTC, danharrin commented on docs-assets/app/resources/views/livewire/panels/navigation/group.blade.php
Can we use the same empty view across multiple pages instead of duplicating?

2025-01-02 09:20 UTC, ModestasV commented on packages/panels/docs/06-navigation.md
> +<AutoScreenshot name="panels/navigation/custom-items" alt="Register Custom Navigation Items" version="3.x" />
Heh, sorry about that! Too used to Title Case :)

2025-02-03 07:59 UTC, danharrin requested changes

2025-02-03 07:59 UTC, danharrin commented on packages/panels/docs/06-navigation.md
> +<AutoScreenshot name="panels/navigation/change-icon" alt=Change navigation items icon version="3.x" />
```suggestion
<AutoScreenshot name="panels/navigation/change-icon" alt="Changed navigation item icon" version="3.x" />
```

2025-02-03 07:59 UTC, danharrin commented on packages/panels/docs/06-navigation.md
> +<AutoScreenshot name="panels/navigation/group" alt="Group navigation items" version="3.x" />
```suggestion
<AutoScreenshot name="panels/navigation/group" alt="Grouped navigation items" version="3.x" />
```

2025-02-03 07:59 UTC, danharrin commented on packages/panels/docs/06-navigation.md
> +<AutoScreenshot name="panels/navigation/custom-items" alt="Register custom navigation items" version="3.x" />
```suggestion
<AutoScreenshot name="panels/navigation/custom-items" alt="Custom navigation items" version="3.x" />
```

2025-02-03 08:00 UTC, merged

2025-02-03 08:00 UTC, danharrin commented
Thanks!