Allow closure based table `Group` labels
laravel-filament/filament pull request #15196
Opened 2024-12-28 17:37 UTC by ralphjsmit

This PR allows the `getLabel()` method of Table Groups to be based on a closure.

2024-12-31 08:05 UTC, danharrin requested changes

2024-12-31 08:05 UTC, danharrin commented on packages/tables/src/Table/Concerns/CanGroupRecords.php
> +        }
If groups are passed in a closure I don't think the table gets passed, I think the table needs to be injected in when the groups property is consumed

2024-12-31 08:05 UTC, danharrin commented on packages/tables/src/Table/Concerns/CanGroupRecords.php
> +        }
Can we move this to the place where the defaultGroup gets read so if we introduce closure support this won't break

2025-01-18 21:23 UTC, ralphjsmit commented on packages/tables/src/Table/Concerns/CanGroupRecords.php
> +        }
Ah you're right, not sure how I missed that. Fixed now!

2025-01-18 21:23 UTC, ralphjsmit commented on packages/tables/src/Table/Concerns/CanGroupRecords.php
> +        }
Done

2025-01-18 21:23 UTC, ralphjsmit commented
Thanks for the review, I just updated it and also pushed a little test.

2025-01-22 08:50 UTC, danharrin requested changes

2025-01-22 08:50 UTC, danharrin commented on tests/src/Tables/TestCase.php
> +            PowerJoinsServiceProvider::class,
Can you move this to the base test case please? There is reasonable possibility we will need this elsewhere in the future.

2025-01-22 08:50 UTC, danharrin commented on tests/src/Tables/GroupingTest.php
Can `invade($livewire)->table` be replaced with `$livewire->getTable()` since it is public?

2025-01-22 17:11 UTC, ralphjsmit commented on tests/src/Tables/TestCase.php
> +            PowerJoinsServiceProvider::class,
Done

2025-01-22 17:12 UTC, ralphjsmit commented on tests/src/Tables/GroupingTest.php
Ah nice, didn't even know that method. Done

2025-01-22 17:51 UTC, merged

2025-01-22 17:51 UTC, danharrin commented
Thanks