Time generate
laravel-filament/filament pull request #15217
Opened 2024-12-31 16:58 UTC by achyutkneupane

## Description

When using `--generate` with `php artisan make:filament-resource`, it detects `date`, `datetime`, and `timestamps` but not `time`.
So, I added the time field and column generation.

## Visual changes

The description seems clear but here is what it generates:

<img width="483" alt="image" src="https://github.com/user-attachments/assets/35657557-1232-4845-a317-e20bbf10ef7b" />

<img width="488" alt="image" src="https://github.com/user-attachments/assets/c614e53c-3659-4a36-a817-57f06b60d291" />

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

2025-01-01 20:09 UTC, danharrin requested changes

2025-01-01 20:09 UTC, danharrin commented on packages/tables/src/Commands/FileGenerators/Concerns/CanGenerateModelTables.php
> +                ])) {
```suggestion
                if ($type['name'] === 'time') {
```

2025-01-02 04:23 UTC, achyutkneupane commented on packages/tables/src/Commands/FileGenerators/Concerns/CanGenerateModelTables.php
> +                ])) {
I followed what was done with the `date` type.

I will make the change accordingly.

2025-01-02 08:14 UTC, danharrin commented on packages/tables/src/Commands/FileGenerators/Concerns/CanGenerateModelTables.php
> +                ])) {
Good spot, I didn't see that. Will fix

2025-01-02 08:15 UTC, merged