Select field on enum type when using generate
laravel-filament/filament pull request #15218
Opened 2024-12-31 18:06 UTC by achyutkneupane

## Description

When using `--generate` with `php artisan make:filament-resource`, `enum` table type will generate `Forms\Components\Select`.

Along with:
- `options` from allowed array
- Default value

It follows the basic label transformation script (kebab -> replace -> ucfirst) for options.

## Visual changes

![image](https://github.com/user-attachments/assets/8093937a-1464-4842-9272-26bc961ca9c0)

![image](https://github.com/user-attachments/assets/e2416a37-c2e7-4ef3-96b7-818d68d8cc72)

![image](https://github.com/user-attachments/assets/04f83e9b-50bd-4e1b-9f0a-9f087c0ab8e0)

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2025-01-02 08:23 UTC, danharrin requested changes
Usually people also pair this with an enum Eloquent model cast, or even use the enum class instead of an enum column. How about detecting on the model if an enum cast is used, and if it is pass the enum class name to the `->options()`? And if there is no enum cast and the column is an enum type, then do this instead.

2025-01-02 17:42 UTC, achyutkneupane commented
@danharrin I got through a lot of research on how to set class as an argument.

Thanks to the `Literal` import you used below, I got the idea.

2025-01-06 03:54 UTC, achyutkneupane reviewed
@danharrin Can you verify the changes?

2025-01-06 10:02 UTC, danharrin commented
Thanks, I will take on the changes from here

2025-02-03 20:22 UTC, danharrin commented
Thanks

2025-02-03 20:23 UTC, merged