Add disable action option
laravel-filament/filament pull request #1929
Opened 2022-03-16 16:34 UTC by a21ns1g4ts

Now we can disable action :)
![disable](https://user-images.githubusercontent.com/11599205/158640362-d5859363-93b1-4762-81cd-1f9ae5c5f342.gif)

2022-03-16 16:54 UTC, ryangjchandler requested changes

2022-03-16 16:54 UTC, ryangjchandler commented on packages/admin/src/Pages/Actions/Concerns/CanBeDisable.php
> +        return $this->isDisabled;
```suggestion
        return value($this->isDisabled);
```

`isDisabled` can be a `Closure` so we need to evaluate it.

2022-03-16 16:55 UTC, ryangjchandler requested changes

2022-03-16 16:55 UTC, ryangjchandler commented on packages/admin/src/Pages/Actions/Concerns/CanBeDisable.php
> +    public function disable(bool | Closure $condition = true): static
```suggestion
    public function disabled(bool | Closure $condition = true): static
```

`disabled` here instead. This is the same name we use elsewhere in Filament.

2022-03-16 17:32 UTC, ryangjchandler approved these changes

2022-03-20 09:21 UTC, merged

2022-03-20 09:21 UTC, danharrin commented
Thank you!