feature: Add support for third level navigation
laravel-filament/filament pull request #4529
Opened 2022-10-13 18:19 UTC by luilliarcec

2022-10-13 19:41 UTC, zepfietje requested changes

2022-10-13 19:41 UTC, zepfietje commented on packages/admin/resources/views/components/layouts/app/sidebar/subgroup.blade.php
> +>
```suggestion
<li
    x-data="{ label: @js($name) }"
    class="filament-sidebar-subgroup overflow-hidden"
>
```

2022-10-13 19:41 UTC, zepfietje commented on packages/admin/resources/views/components/layouts/app/sidebar/subgroup.blade.php
> +                ])" x-bind:class="$store.sidebar.groupIsCollapsed(label) || '-rotate-180'" x-cloak/>
```suggestion
                <x-heroicon-o-chevron-down
                    :class="\Illuminate\Support\Arr::toCssClasses([
                        'w-3 h-3 text-gray-600 transition',
                        'dark:text-gray-300' => config('filament.dark_mode'),
                    ])"
                    x-bind:class="$store.sidebar.groupIsCollapsed(label) || '-rotate-180'"
                    x-cloak
                />
```

2022-10-13 19:41 UTC, zepfietje commented on packages/admin/resources/views/components/layouts/app/sidebar/subgroup.blade.php
> +        x-show="! ($store.sidebar.groupIsCollapsed(label) && {{ config('filament.layout.sidebar.is_collapsible_on_desktop') ? '$store.sidebar.isOpen' : 'true' }})"
```suggestion
        x-show="!($store.sidebar.groupIsCollapsed(label) && {{ config('filament.layout.sidebar.is_collapsible_on_desktop') ? '$store.sidebar.isOpen' : 'true' }})"
```

2022-10-13 19:41 UTC, zepfietje commented on packages/admin/src/FilamentManager.php
> +                                    ->items($items)
```suggestion
                                    ->items($items),
```

2022-10-13 19:41 UTC, zepfietje commented on packages/admin/src/FilamentManager.php
> +                        $items->filter(fn (Navigation\NavigationItem $item): bool => $item->getSubgroup() === null)
```suggestion
                        $items->filter(fn (Navigation\NavigationItem $item): bool => $item->getSubgroup() === null),
```

2022-10-13 20:28 UTC, zepfietje requested changes

2022-10-13 20:28 UTC, zepfietje commented on packages/admin/src/FilamentManager.php
> +                            )
```suggestion
                            ),
```

2022-10-14 20:16 UTC, danharrin commented
Hey, there is alot of complexity here because we're allowing resources and pages to register subgroups. Personally I think this should only be an option for the [Advanced Navigation API](https://filamentphp.com/docs/2.x/admin/navigation#advanced-navigation-customization). Also, please add docs so I know how to use it.

2022-10-19 05:43 UTC, Nuhel commented
> Hey, there is alot of complexity here because we're allowing resources and pages to register subgroups. Personally I think this should only be an option for the [Advanced Navigation API](https://filamentphp.com/docs/2.x/admin/navigation#advanced-navigation-customization). Also, please add docs so I know how to use it.

I think it wil be nice, If there is a class NavigationGrouo like NavigationItem class, And NavigationGrouo allow both NavigationItem and NavigationGroup as child. When there is NavigationGroup as child, It will be rendered as a group.

2022-10-19 08:09 UTC, danharrin commented
yeah I agree with @Nuhel, introducing a "subgroup" is not optimal when we could just support nested groups

2022-10-20 13:02 UTC, Nuhel commented
I have added support for multilevel menu, [You can have a look](https://drive.google.com/file/d/1mKdPiEoCZ1RThOOZ_WeBTof6eGx7V5OG/view?usp=sharing).

If you like this I will make an pr.

2022-10-20 13:48 UTC, danharrin commented
I don't care about the design, if the backend implementation is not good enough then it will not be merged.

2022-10-20 14:07 UTC, Nuhel commented
> I don't care about the design, we can fix that. If the backend implementation is not good enough then it will not be merged.

Yes I know, I just wanted to be sure, If the design is very bad , i would try to fix the design and than make an PR.

2022-10-22 10:55 UTC, danharrin commented
Closing in favour of #4650

2022-10-22 10:55 UTC, closed without merging