new Section::make()->aside() to align Heading & Description
laravel-filament/filament pull request #4530
Opened 2022-10-13 19:22 UTC by mikrosmile

new Section::make()->aside() to align Heading & Description on the left and content (form components inside ->schema([])) on the right

2022-10-14 05:42 UTC, ManojKiranA commented
based on #4519

2022-10-14 07:31 UTC, zepfietje requested changes

2022-10-14 07:31 UTC, zepfietje commented on packages/forms/resources/views/components/section.blade.php
> +        'md:grid grid-cols-2 flex-row' => $isAside(),
```suggestion
        'flex-row md:grid md:grid-cols-2' => $isAside(),
```

2022-10-14 07:31 UTC, zepfietje commented on packages/forms/resources/views/components/section.blade.php
> +            'bg-white rounded-xl border border-gray-300' => $isAside(),
```suggestion
            'rounded-xl border border-gray-300 bg-white' => $isAside(),
```

2022-10-14 07:31 UTC, zepfietje commented on packages/forms/resources/views/components/section.blade.php
> +            'align-top flex px-0' => $isAside(),
```suggestion
            'flex px-0 align-top' => $isAside(),
```

2022-10-14 07:31 UTC, zepfietje commented on packages/forms/resources/views/components/section.blade.php
> +        'filament-forms-section-component bg-white rounded-xl border border-gray-300' => ! $isAside(),
```suggestion
        'filament-forms-section-component rounded-xl border border-gray-300 bg-white' => ! $isAside(),
```

2022-10-15 08:00 UTC, danharrin commented
Thanks!

2022-10-15 08:00 UTC, merged