Feature: Add select /deselect all to Checkbox List
laravel-filament/filament pull request #4766
Opened 2022-10-31 17:29 UTC by awcodes

Adds optional `canSelectAll()` method to CheckboxList form component to allow selecting and deselecting all options at once.

2022-10-31 21:13 UTC, zepfietje requested changes

2022-10-31 21:13 UTC, zepfietje commented on packages/forms/docs/03-fields.md
> +You may also allow user to select / deselect all options at once by using the `canSelectAll()` method:
```suggestion
You may also allow users to select/deselect all options at once using the `canSelectAll()` method:
```

2022-10-31 21:13 UTC, zepfietje commented on packages/forms/resources/lang/en/components.php
> +    ],
```suggestion
    ],

```

2022-10-31 21:13 UTC, zepfietje commented on packages/forms/resources/lang/en/components.php
> +            ],
```suggestion
            'deselect_all' => [
                'label' => 'Deselect all',
            ],

            'select_all' => [
                'label' => 'Select all',
            ],
```

2022-11-01 14:53 UTC, danharrin commented on packages/forms/src/Components/CheckboxList.php
> +    public function toggleable(bool | Closure $condition = true): static
```suggestion
    public function bulkToggleable(bool | Closure $condition = true): static
```

2022-11-03 09:21 UTC, zepfietje commented
@danharrin, any action needed on this PR?

2022-11-03 09:24 UTC, danharrin commented on packages/forms/docs/03-fields.md
> +You may also allow users to select/deselect all options at once using the `bulkToggleable()` method:
```suggestion
You may also allow users to toggle all checkboxes at once using the `bulkToggleable()` method:
```

2022-11-03 09:29 UTC, merged