Wizard: Expose step value to querystring
laravel-filament/filament pull request #4788
Opened 2022-11-01 23:19 UTC by SquidwardHill

Signed-off-by: Sydney Hill <sydneyehill@gmail.com>

2022-11-02 22:59 UTC, danharrin requested changes
You might need to rename other method and property references to match these

2022-11-02 22:59 UTC, danharrin commented on packages/forms/src/Components/Wizard.php
> +    public ?int $currentStep = null;
I think this is not being used?

2022-11-02 22:59 UTC, danharrin commented on packages/forms/src/Components/Wizard.php
> +    protected bool | Closure $stepAsQuerystring = false;
```suggestion
    protected bool | Closure $isStepInQueryString = false;
```

2022-11-02 22:59 UTC, danharrin commented on packages/forms/src/Components/Wizard.php
> +    public function setStepAsQuerystring(bool | Closure $condition = true): static
```suggestion
    public function queryStringStep(bool | Closure $condition = true): static
```

2022-11-02 22:59 UTC, danharrin commented on packages/forms/src/Components/Wizard.php
> +    public function isStepAsQuerystring(): bool
```suggestion
    public function isStepInQueryString(): bool
```

2022-11-02 23:00 UTC, danharrin commented
@zepfietje @awcodes wdyt about naming that I proposed? it's difficult

2022-11-02 23:30 UTC, awcodes commented
I think they are ok.

2022-11-03 09:03 UTC, zepfietje commented
I'd prefer something like `storeStepInQueryString()` with `shouldStoreStepInQueryString()`. Quite lengthy though.

Also, I'm wondering what's the purpose of storing the step in the query string if the step is not restored from the query string when loading the page anyway?

2022-11-03 09:04 UTC, danharrin commented
How about `persistStepInQueryString()`? And yes, it should be restored on load

2022-11-03 09:21 UTC, zepfietje commented
I like that. Think it matches the naming around table filters.

2022-11-03 09:23 UTC, danharrin commented
Okay, lets use that naming then @SquidwardHill 

`persistStepInQueryString()`
`$isStepPersistedInQueryString` / `isStepPersistedInQueryString()`

2022-11-03 09:29 UTC, zepfietje commented
`isPersisted` or `shouldPersist`, @danharrin?

2022-11-03 09:37 UTC, danharrin commented
I try and use `is` wherever it makes gramatical sense. `should` is a last resort

2022-11-03 09:41 UTC, zepfietje commented
Makes sense! Still waiting for your method naming docs. 😉

2022-11-03 20:53 UTC, lhilton commented
> Also, I'm wondering what's the purpose of storing the step in the query string if the step is not restored from the query string when loading the page anyway?

Speaking to this question, I can add some context: When we developed this PR, the decision was to make the minimal filament-side change possible and let the handling of that be on the consumer side. In other words, leave it to the end forms to determine the right way to respond to that querystring. I can see a case for going the other route, however this would require more substantial design in order to both support the change and allow developer overrides of that behavior.

2022-11-03 20:59 UTC, zepfietje commented
Thanks for clarifying, @lhilton! I think it's important to add the full functionality to Filament if we're going to add it.

2022-11-03 21:01 UTC, lhilton commented
@danharrin @zepfietje I'll coordinate with @SquidwardHill to move our restoration logic in as part of this PR then. Thank you for the feedback!

2022-11-04 22:21 UTC, SquidwardHill commented
Circling back to this on Monday.

2022-11-14 14:21 UTC, zepfietje commented
Any update on this PR @lhilton @SquidwardHill?

2022-11-17 17:33 UTC, lhilton commented
We have updated this PR with the requested changes (name changes) and we moved the logic to automatically restore step state if the feature is in use.

Additionally we found a need to modify the querystring key in use. This was previously hardcoded to `step`. It will now default to the value `step` but can be overridden when using the `persistStepInQueryString()` function as an optional second parameter.

2022-11-17 19:39 UTC, merged

2022-11-17 19:39 UTC, danharrin commented
Thanks!