feat: add `registerThemeUsingVite`
laravel-filament/filament pull request #4891
Opened 2022-11-10 15:39 UTC by innocenzi

This pull request is an attempt at providing a better solution for using a theme with Vite. 

A new `registerThemeUsingVite` is introduced: it accepts a single or a list of assets, as well as a build directory as the second parameter.

```php
Filament::registerThemeUsingVite('resources/css/filament.css');
```

I think this is cleaner than the current recommended approach:

```php
Filament::registerTheme(
    app(Vite::class)('resources/css/filament.css'),
);
```

I would understand if you think this is superfluous though.

2022-11-10 15:45 UTC, innocenzi commented
> using VuePress' built-in support for Laravel Mix / Webpack Encore via Illuminate\Foundation\Vue::class(). This allows us to use webpack mix() or encore() functions inside our themes without having to manually add them into every single blade file we create!

Not quite riiight haha. Good bot though.

2022-11-10 17:30 UTC, danharrin commented on packages/admin/src/FilamentManager.php
> +        $this->viteTheme = $theme;
New properties don't need introducing, we can just call `app(Vite::class)` and pass it to `$this->theme`

2022-11-10 17:30 UTC, danharrin commented on packages/admin/src/FilamentManager.php
> +    public function registerThemeUsingVite(string | array $theme, string $buildDirectory = null): void
We could name this just `registerViteTheme`

2022-11-10 17:32 UTC, danharrin commented
> Not quite riiight haha. Good bot though.

Don't be mean, it got excited at the end! (Yay!) 😂

2022-11-11 10:28 UTC, innocenzi commented
I applied the recommended changes — my initial thoughts for the added properties was to not call `Vite` inside the setter, but you're right, it's better this way 👍

2022-11-11 11:42 UTC, danharrin commented
Cool, might be worth updating the docs example too?

2022-11-11 12:01 UTC, innocenzi commented
Woops, definitely. Done

2022-11-11 12:29 UTC, zepfietje commented
I feel like we should also have a method for Laravel Mix if we add one for Vite...

2022-11-11 12:30 UTC, zepfietje requested changes

2022-11-11 12:30 UTC, zepfietje commented on packages/admin/src/FilamentManager.php
> +        $this->theme = app(\Illuminate\Foundation\Vite::class)($theme, $buildDirectory);
Could you import the namespace at the top of the file?

2022-11-11 13:02 UTC, merged

2022-11-11 13:05 UTC, innocenzi commented
> I feel like we should also have a method for Laravel Mix if we add one for Vite...

I understand the feeling, but the syntax for Vite is more cumbersome than Mix's. Whereas there is the `mix` helper, there is no similar `vite` function -- you need to resolve Vite from the container before calling it, making the syntax quite bad in that situation, in my opinion.

2022-11-11 15:33 UTC, zepfietje commented
Yeah I agree, but still feels weird to have this new method since Vite is Laravel's default now.