[DOC] Individual search in query string
laravel-filament/filament pull request #4955
Opened 2022-11-15 13:11 UTC by Sicklou

I added the information of how getting the individual search into the query string, since nothing was written in the doc.

2022-11-15 13:24 UTC, zepfietje requested changes

2022-11-15 13:24 UTC, zepfietje commented on packages/tables/docs/02-getting-started.md
> +    'tableColumnSearchQueries',  // For individual search
```suggestion
    'tableSearchQuery' => ['except' => ''],
    'tableColumnSearchQueries',
```

2022-11-15 13:24 UTC, zepfietje commented on packages/tables/docs/03-columns/01-getting-started.md
> +If you want to have the search persisted in the query string, you have to add `tableColumnSearchQueries` to the `queryString` property :
```suggestion
You may optionally persist the search in the query string:
```

2022-11-15 13:24 UTC, zepfietje commented on packages/tables/docs/03-columns/01-getting-started.md
> +    ];
```suggestion
protected $queryString = [
    ...,
    'tableColumnSearchQueries',
];
```

2022-11-15 13:25 UTC, zepfietje requested changes

2022-11-15 13:25 UTC, zepfietje commented on packages/tables/docs/03-columns/01-getting-started.md
> +    ...,
```suggestion
    // ...
```

2022-11-15 13:28 UTC, zepfietje approved these changes

2022-11-15 14:54 UTC, Sicklou commented
Thanks for the review.

2022-11-17 09:33 UTC, danharrin commented on packages/tables/docs/03-columns/01-getting-started.md
> +You may optionally persist the search in the query string:
```suggestion
You may optionally persist the searches in the query string:
```

2022-11-17 09:33 UTC, merged