Feat: Add conditional to trigger modal visibility on actions.
laravel-filament/filament pull request #5252
Opened 2022-12-14 14:13 UTC by awcodes

This is for the discussion on discord for allowing conditional rendering of action modals.

2022-12-14 14:27 UTC, zepfietje requested changes

2022-12-14 14:27 UTC, zepfietje commented on packages/admin/docs/03-pages/02-actions.md
> +### Conditional Rendering
```suggestion
### Conditional rendering
```

2022-12-15 12:07 UTC, danharrin commented on packages/support/src/Actions/Concerns/CanOpenModal.php
> +        return ! $this->isModalHidden() && ($this->hasFormSchema() || $this->getModalSubheading() || $this->getModalContent() || $this->getModalFooter());
```suggestion
        return (! $this->isModalHidden()) && ($this->hasFormSchema() || $this->getModalSubheading() || $this->getModalContent() || $this->getModalFooter());
```

2022-12-15 12:08 UTC, danharrin commented on packages/admin/docs/03-pages/02-actions.md
> +    ->modalHidden(fn ($livewire) => $livewire->data['role'] != 'admin')
```suggestion
    ->modalHidden(fn (): bool => $this->role !== 'admin')
```

2022-12-15 12:21 UTC, merged