Fix: Global search hidden action
laravel-filament/filament pull request #5278
Opened 2022-12-17 11:21 UTC by ArtMin96

Global search action does not hide when hidden is true.

2022-12-17 17:36 UTC, zepfietje requested changes

2022-12-17 17:36 UTC, zepfietje commented on packages/admin/resources/views/components/global-search/actions/index.blade.php
> +        @if(! $action->isHidden())
```suggestion
        @unless ($action->isHidden())
```

2022-12-17 17:36 UTC, zepfietje commented on packages/admin/resources/views/components/global-search/actions/index.blade.php
> +        @endif
```suggestion
        @endunless
```

2022-12-17 18:47 UTC, ArtMin96 commented
Ready

2022-12-18 15:49 UTC, merged

2022-12-18 15:49 UTC, danharrin commented
Thanks