Fix: modal height bug
laravel-filament/filament pull request #5582
Opened 2023-01-30 17:22 UTC by awcodes

Resolves #5228 

Theoretically, this should fix the issue, but I have no way to test an iPhone6s.

2023-01-30 19:59 UTC, zepfietje commented
Haven't tested this, but the classes you added to `html` and `body` are exactly what I have in a non-Filament project of mine.

Should we still test this, or let @szommeragi pull in these changes?

If there's no other issues being introduced by this change, I think it looks ok.

2023-01-30 20:05 UTC, awcodes commented
Honestly, I don't know any way to test it. Everything else still functions normally as best I can tell in the demo with the changes.

2023-01-30 20:07 UTC, zepfietje commented
I can pull in the changes and run it on my iPhone.

2023-01-30 20:11 UTC, awcodes commented
Do you have an iPhone 6? I guess the issue would be the same on a 13 too though.

2023-01-30 20:19 UTC, zepfietje commented
I have a 12 mini, so small enough to reproduce. 😆

Been able to reproduce the issue, also with this PR.
So this doesn't fix it unfortunately.

Seems like it might have something to do with not being able to scroll when the modal is open?
When the browser tab bar is hidden (by first scrolling down), the modal shows just fine.
However, when showing the tab bar again, there's no way to hide it.

2023-01-30 22:31 UTC, awcodes commented
I wonder if the modal content just needs to set to overflow scroll, so the modal itself can't be larger than the available total height.

2023-01-31 07:16 UTC, zepfietje commented
Hmm, not sure if that'd fix it.
The modal content doesn't seem to overflow.

2023-02-01 21:08 UTC, awcodes commented
Think i got this @zepfietje.

2023-02-01 22:45 UTC, awcodes commented
Used valet share to ngrok to my phone and the modal itself was scrollable with the latest commit. But please check on your end too.

2023-02-02 08:58 UTC, zepfietje requested changes
Just fixing the order.

2023-02-02 08:58 UTC, zepfietje commented on packages/admin/resources/views/components/layouts/base.blade.php
> +    class="antialiased bg-gray-100 filament js-focus-visible h-full"
```suggestion
    class="filament js-focus-visible h-full bg-gray-100 antialiased"
```

2023-02-02 08:58 UTC, zepfietje commented on packages/admin/resources/views/components/layouts/app.blade.php
> +    <div class="filament-app-layout flex w-full min-h-full overflow-x-clip">
```suggestion
    <div class="filament-app-layout flex min-h-full w-full overflow-x-clip">
```

2023-02-02 08:58 UTC, zepfietje commented on packages/admin/resources/views/components/layouts/base.blade.php
> +        'filament-body bg-gray-100 text-gray-900 min-h-full',
```suggestion
        'filament-body min-h-full bg-gray-100 text-gray-900',
```

2023-02-02 09:05 UTC, zepfietje commented
Confirmed this fixes the issue indeed.

Really great work on fixing this one, @awcodes! 💪

This can now be merged, @danharrin. 😄

2023-02-02 09:05 UTC, zepfietje approved these changes

2023-02-02 10:58 UTC, merged

2023-02-02 10:58 UTC, danharrin commented
Thanks so much @awcodes !