Add deferred loading on table
laravel-filament/filament pull request #5629
Opened 2023-02-07 21:51 UTC by Sicklou

Hello,

This is the first time I make a PR on a feature, I'm aware it is not perfect at first try.
I know my naming choices are probably not good. Maybe I put some code at the wrong place.

So, this PR adds a way to defer the loading of data by exploiting the `wire:init` directive of livewire.

To make it work with a table resource, juste use the `deferLoading()` method : 
```php
public static function table(Table $table): Table
{
    return $table
        ->columns([
            TextColumn::make('name')
        ])
        ->actions([
            Tables\Actions\EditAction::make(),
        ])
        ->bulkActions([
            Tables\Actions\DeleteBulkAction::make(),
        ])
        ->deferLoading();
}
```

To use it with the standalone package, `true` will defer loading, `false` will load data at the page loading.
```php
 public function isLoadingDeferred(): bool
 {
      return true;
 }
```

2023-02-13 23:03 UTC, danharrin commented
Hey! A few things...

- PHPStan failing
- Please rename methods and properties in the CanDeferLoading to include "table", so they don't get confused with other methods on the Livewire component. `$isTableLoaded`, `isTableLoadingDeferred()`, `isTableLoaded()`. `allowLoadingData()` can be removed as it does the same as `isTableLoaded()`.
- Instead of returning an empty collection, wrap the table contents in an `@if ($isTableLoaded)` instead.

2023-02-14 13:08 UTC, Sicklou commented
Thanks for the review.

I made the changes but if I wrap the table contents instead of returning an empty collection, the query run when the page loads, since the `getRecords` is called.
Which is what I want to avoid with this PR.

Do you see a way to do it ?

2023-02-14 13:11 UTC, danharrin commented
You can move the `$getRecords()` etc inside the `@if`

2023-02-14 20:32 UTC, danharrin commented
I think we need some sort of loading indicator when the records are not present. We should default the `$records` to be `null` instead and use `$records === null` and render the `<x-filament-support::loading-indicator />` like we do in other places

2023-02-15 09:13 UTC, Sicklou commented
Just added a loading indicator, it is nicer now

2023-02-15 09:17 UTC, zepfietje requested changes

2023-02-15 09:17 UTC, zepfietje commented on packages/tables/resources/views/index.blade.php
> +                @elseif (count($records))
Could you fix indentation here, @Sicklou?

2023-02-15 09:17 UTC, zepfietje commented on packages/tables/resources/views/index.blade.php
> +                    </tr>
And here.

2023-02-18 12:20 UTC, merged

2023-02-18 12:21 UTC, danharrin commented
Thanks

2023-02-18 13:01 UTC, Sicklou commented
Maybe it would be nice to mention it in the documentation. But Im not sure where it can be added

2023-02-18 13:03 UTC, danharrin commented
I've added it in the v3 docs, I'm not sure where to put it in v2.

2023-02-18 16:02 UTC, archilex commented
Great PR @Sicklou! I’ve already implemented it in my resources. Very nice! 👏

I did notice that on mobile with lots of columns since the loading indicator is centered, you don’t see it. I’m wondering if changing it for `<x-tables::loading-cell>` would be a viable option so that you can see the loading animation on any size?

Potentially you could even get the default pagination count and render the entire table? Not sure. I haven’t looked into it as I’m on my phone. 

Thoughts?

2023-02-18 17:20 UTC, archilex commented
Just PRed the change to see if the group likes it. #5731