Add placeholder to search input in Select component
laravel-filament/filament pull request #6140
Opened 2023-04-06 21:09 UTC by dmandrade

Add option to set a placeholder in the search field providing a better ux when the select already has preloaded data.

![image](https://user-images.githubusercontent.com/7275012/230494207-bf658272-d6dd-4a63-8a6f-27edfc63f577.png)
![image](https://user-images.githubusercontent.com/7275012/230494486-3b910d8f-6120-4c42-a1c3-8ba942aea240.png)

2023-04-07 09:15 UTC, zepfietje commented on packages/forms/resources/js/components/select.js
> +                        searchPlaceholderValue: searchPlaceholder,
```suggestion
                        searchPlaceholderValue: searchPlaceholder,
                        searchResultLimit: optionsLimit,
```

2023-04-07 09:15 UTC, zepfietje commented on packages/forms/resources/js/components/select.js
> +            searchPlaceholder,
```suggestion
            searchPlaceholder,
            searchPrompt,
```

2023-04-07 09:16 UTC, zepfietje commented on packages/forms/resources/lang/en/components.php
> +
```suggestion

        'search_placeholder' => 'Search',

        'search_prompt' => 'Start typing to search...',
```

2023-04-07 09:16 UTC, zepfietje commented on packages/forms/resources/lang/en/components.php
> +        'search_prompt' => 'Start typing to search...',
```suggestion
        'search_prompt' => 'Start typing to search...',

```

2023-04-07 09:17 UTC, zepfietje commented on packages/forms/resources/lang/pt_BR/components.php
> +        'search_placeholder' => 'Buscar',
```suggestion
        'search_placeholder' => 'Buscar',

        'search_prompt' => 'Comece a digitar para pesquisar...',

```

2023-04-07 09:17 UTC, zepfietje commented on packages/forms/resources/views/components/select.blade.php
> +                        searchPlaceholder: @js($getSearchPlaceholder()),
```suggestion
                        searchPlaceholder: @js($getSearchPlaceholder()),
                        searchPrompt: @js($getSearchPrompt()),
```

2023-04-07 09:18 UTC, zepfietje commented on packages/forms/src/Components/Concerns/CanBeSearchable.php
> +    protected string | Closure | null $searchPlaceholder = null;
```suggestion
    protected string | Closure | null $searchPlaceholder = null;

    protected string | Htmlable | Closure | null $searchPrompt = null;
```

2023-04-07 09:20 UTC, zepfietje requested changes
Mark as ready for review when done.

2023-04-07 09:20 UTC, zepfietje commented on packages/forms/src/Components/Concerns/CanBeSearchable.php
> +
Could you move this above `searchPrompt` to ensure alphabetical sort, @dmandrade?

2023-04-07 09:20 UTC, zepfietje commented on packages/forms/src/Components/Concerns/CanBeSearchable.php
> +
Move this too.

2023-04-07 11:07 UTC, danharrin commented
Why can't we use the existing `searchPrompt()`?

2023-04-07 12:22 UTC, dmandrade commented
> Why can't we use the existing `searchPrompt()`?

I thought about it but I believe that choicesjs will always display a message under the search field when there are no preloaded items, so I thought it best to add one more configuration option.

2023-04-07 12:36 UTC, zepfietje commented
Can we hide the prompt? Then just displaying the placeholder instead should be fine maybe?

2023-04-07 12:41 UTC, dmandrade commented
Can I do that, do you think it would be a better ux just display the input with placeholder inside?

2023-04-07 14:22 UTC, danharrin commented
We shouldnt need to add any more methods to the class to do this

2023-04-10 13:44 UTC, dmandrade commented
New methods have been removed and the class is as it was before.
just passing the searchPrompt as placeholder and hiding the "has-no-choices" element when the field is a single selection.

2023-04-10 19:02 UTC, merged

2023-04-10 19:02 UTC, danharrin commented
Thanks