Do not send unnecessary headers when pretending to be a file
laravel-filament/filament pull request #6407
Opened 2023-05-04 16:59 UTC by linaspasv

This PR enhances the handling of Set-Cookie headers, which Laravel typically includes in every request. By preventing these headers, files can more effectively simulate being the requested assets. Additionally, this change has a positive impact on CloudFlare caching since CloudFlare bypasses all requests containing Set-Cookie headers, including static assets. This update ensures better caching behavior and improves overall performance.

2023-05-04 18:59 UTC, zepfietje requested changes

2023-05-04 18:59 UTC, zepfietje commented on packages/admin/src/Http/Controllers/AssetController.php
> +        ])->send();
Could you put each chained method after `response()` on its own line?
Mark as ready when done. 😊

2023-05-04 22:45 UTC, merged

2023-05-04 22:45 UTC, danharrin commented
Thanks

2023-05-05 08:35 UTC, danharrin commented
This caused many major issues for people using Filament on Laragon this morning. Reverted.

2023-05-05 08:39 UTC, linaspasv commented
> 

What kind of issues?

2023-05-05 08:48 UTC, zepfietje commented
> What kind of issues?

https://discord.com/channels/883083792112300104/1103955443656708169