Fix PostgreSQL data type incompatibility issue in Laravel Notification query
laravel-filament/filament pull request #6439
Opened 2023-05-06 22:25 UTC by a21ns1g4ts

This PR fixes an issue in Laravel where notifications stored in a PostgreSQL database with a TEXT column were not being queried correctly. Specifically, when searching for notifications where the "format" key in the JSON column was set to "filament", the query was not returning the expected results.

The issue was due to a data type incompatibility between Laravel and PostgreSQL. Laravel defined the "data" column as type "text", while PostgreSQL used type "json". To resolve the issue, this PR updates the query to use the appropriate syntax for each database driver. For PostgreSQL, the query now uses the "json" data type and searches for the key "format" using the "->" operator. For all other drivers, the query continues to use the "text" data type and searches for the string '%"format":"filament"%' using the "like" operator.

This fix ensures that notifications are queried correctly regardless of the underlying database driver, allowing for consistent behavior across different database setups.

2023-05-07 00:09 UTC, mackhankins commented
Thank You!  Hoping this gets approved soon.

2023-05-07 07:12 UTC, zepfietje requested changes

2023-05-07 07:12 UTC, zepfietje commented on packages/notifications/src/Http/Livewire/Notifications.php
> +        return match ($this->getUser()->notifications()->getConnection()->getDriverName()) {
Could you extract `$this->getUser()->notifications()` to `$query` just above the match expression?

2023-05-07 07:13 UTC, zepfietje commented on packages/notifications/src/Http/Livewire/Notifications.php
> +        return match ($this->getUser()->notifications()->getConnection()->getDriverName()) {
Mark as ready for review when done please.

2023-05-07 08:18 UTC, zepfietje commented on packages/notifications/src/Http/Livewire/Notifications.php
> +            default => $query->notifications()->where('data->format', 'filament'),
```suggestion
            'pgsql' => $query->where('data', 'like', '%"format":"filament"%'),
            default => $query->where('data->format', 'filament'),
```

2023-05-07 15:20 UTC, a21ns1g4ts reviewed
Good. I was unsleeping at last night. :sleepy:

2023-05-08 11:26 UTC, danharrin commented
To be honest, I don't like the use of `like` to get a JSON property. We have this note in the docs about just using a `json()` column, does this not work?

<img width="892" alt="Screenshot 2023-05-08 at 12 24 23" src="https://user-images.githubusercontent.com/41773797/236811713-2587c465-680f-492e-894c-4f82cc1ea71e.png">

2023-05-08 12:59 UTC, a21ns1g4ts commented
@danharrin You are right. It is much easier to change the type to JSON, but currently this field stores other things that are not JSON. Anyway, we can simply make it easier to extend this behavior.

2023-05-08 13:04 UTC, danharrin commented
The field shouldn't store anything apart from JSON if it should work with Filament notifications

2023-05-08 13:21 UTC, a21ns1g4ts commented
What is the best way to extend this functionality without modifying the package code ?

2023-05-08 13:24 UTC, danharrin commented
Extend `Notifications`, override `getDatabaseNotificationsQuery()` and use that as the LW component instead.

But I would urge you to not store plain text in that column. JSON is the only thing that will work.

2023-05-08 13:24 UTC, closed without merging