Update Italian create modal translations
laravel-filament/filament pull request #6478
Opened 2023-05-10 14:01 UTC by slamservice

Italian translation upgrade

2023-05-10 16:50 UTC, Simoneu01 requested changes

2023-05-10 16:50 UTC, Simoneu01 commented on packages/support/resources/lang/it/actions/create.php
> +            'heading' => 'Slava :label',
Qui c'è un typo

2023-05-10 16:50 UTC, Simoneu01 commented on packages/support/resources/lang/it/actions/create.php
> +                    'label' => 'Salva & un altro nuovo',
Qui si potrebbe mettere "Salva e crea uno nuovo "

2023-05-12 06:54 UTC, zepfietje commented
Could you implement the requested changes so this PR can be merged, @slamservice?

2023-05-12 08:45 UTC, zepfietje commented on packages/support/resources/lang/it/actions/create.php
> +                    'label' => 'Salva & un altro nuovo',
```suggestion
                    'label' => 'Salva & crea uno nuovo',
```

2023-05-12 08:54 UTC, merged