Make FileUpload croppable
laravel-filament/filament pull request #6491
Opened 2023-05-11 17:37 UTC by tanthammar

Add support for Cropper.js
https://github.com/fengyuanchen/cropperjs
via Filepond image edit plugin
https://pqina.nl/filepond/docs/api/plugins/image-edit/

2023-05-12 06:37 UTC, zepfietje requested changes
Left some quick initial comments, mostly around code style.

2023-05-12 06:37 UTC, zepfietje commented on bin/build.mjs
> +    }
Please don't use abbreviations. 😄

2023-05-12 06:37 UTC, zepfietje commented on package.json
>          "dev:js": "node bin/build.mjs --dev",
Please keep the order or also move the js scripts.

2023-05-12 06:37 UTC, zepfietje commented on packages/forms/resources/js/components/file-upload.js
> +import Cropper from 'cropperjs'
Alphabetical order.

2023-05-12 06:37 UTC, zepfietje commented on packages/forms/resources/js/components/file-upload.js
> +FilePond.registerPlugin(FilePondPluginImageEdit)
Order.

2023-05-12 06:37 UTC, zepfietje commented on packages/forms/resources/js/components/file-upload.js
> +    fillColor,
Order alpha.

2023-05-12 06:37 UTC, zepfietje commented on packages/forms/resources/js/components/file-upload.js
> +        cropper: {},
Same for these.

2023-05-12 06:37 UTC, zepfietje commented on packages/forms/resources/js/components/file-upload.js
> +            this.cropper = null
```suggestion
            this.cropper = null

```

2023-05-12 06:37 UTC, zepfietje commented on packages/forms/resources/js/index.js
> +import 'cropperjs/dist/cropper.min.css'
Order.

2023-05-12 06:37 UTC, zepfietje commented on packages/forms/resources/js/components/file-upload.js
> +            this.cropper = null
```suggestion
            this.cropper.destroy()
            this.cropper = null

```

2023-05-12 06:37 UTC, zepfietje commented on packages/forms/resources/lang/en/components.php
> +    ],
Order.

2023-05-12 06:37 UTC, zepfietje commented on packages/forms/resources/lang/sv/components.php
> +        'flip-vertical' => 'Vänd bilden vertikalt',
Order.

2023-05-12 06:37 UTC, zepfietje commented on packages/forms/resources/views/components/file-upload.blade.php
> +        $cropperActiveBtnClass = 'bg-gray-200 text-gray-800 dark:bg-gray-600 dark:text-white';
Order.

2023-05-12 09:28 UTC, tanthammar commented
Hi @zepfietje I think you and Dan are supposed to adopt this and make it yours . So you are free to make all the changes you want :)

2023-05-12 09:28 UTC, tanthammar commented on bin/build.mjs
> +    }
I don't know what abbreviations mean ...

2023-05-12 09:31 UTC, tanthammar commented on packages/forms/resources/views/components/file-upload.blade.php
> +        $cropperActiveBtnClass = 'bg-gray-200 text-gray-800 dark:bg-gray-600 dark:text-white';
?

2023-05-12 09:35 UTC, zepfietje commented on packages/forms/resources/views/components/file-upload.blade.php
> +        $cropperActiveBtnClass = 'bg-gray-200 text-gray-800 dark:bg-gray-600 dark:text-white';
Alphabetically.

2023-05-12 09:37 UTC, zepfietje commented
We'll definitely do final tweaks, but if you could get some simple changes done, that'd save us time and allow us to review and merge the PR quicker.

In general, properties/variables are sorted alphabetically.
That's the main change I requested for now. 🙂

2023-05-12 12:46 UTC, tanthammar commented
Tried to sort.

2023-06-09 23:22 UTC, awcodes commented
@zepfietje I've updated this with similar styles to curators implantation. So unless Dan or Tina are still working on functionality I think it might be ready for review.

2023-06-10 12:56 UTC, zepfietje commented
> @zepfietje I've updated this with similar styles to curators implantation. So unless Dan or Tina are still working on functionality I think it might be ready for review.

Okay thanks, Adam.
Could @tanthammar and @danharrin confirm this requires my review now?

2023-07-15 22:41 UTC, danharrin approved these changes

2023-07-15 22:41 UTC, danharrin commented
@zepfietje ready for your review, I am happy

2023-07-19 16:41 UTC, merged