Navigation item additional methods
laravel-filament/filament pull request #6602
Opened 2023-05-23 16:08 UTC by ousid

Based on the discussion in https://github.com/filamentphp/filament/discussions/6566, this PR add the ability to show/hide the custom navigation items, by setting `visible` or `hidden` method to the custom item.

### Example
```php
use Filament\Facades\Filament;
use Filament\Navigation\NavigationItem;

Filament::serving(function () {
    Filament::registerNavigationItems([
        NavigationItem::make('Analytics')
            ->visible(false)
            // or
            ->hidden(true),
    ]);
});
```

2023-05-28 08:11 UTC, danharrin requested changes

2023-05-28 08:11 UTC, danharrin commented on packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
> +    'hidden' => null,
I don't think any views need to be changed to accommodate this. If a navigation item is hidden, then it should not be in the array of items in the first place

2023-05-28 08:11 UTC, danharrin commented on packages/admin/src/Navigation/NavigationItem.php
> +    protected ?bool $isVisible = null;
```suggestion
    protected bool $isHidden = null;

    protected bool $isVisible = true;
```

2023-05-28 08:11 UTC, danharrin commented on packages/admin/src/Navigation/NavigationItem.php
> +    }
```suggestion
    public function visible(bool | Closure $condition = true): static
    {
        $this->isVisible = value($condition);

        return $this;
    }

    public function hidden(bool | Closure $condition = true): static
    {
        $this->isHidden = value($condition);

        return $this;
    }
```

2023-05-28 08:11 UTC, danharrin commented on packages/admin/src/Navigation/NavigationItem.php
> +        return $this->isVisible;
```suggestion
        return ! $this->isHidden();
```

2023-05-28 08:11 UTC, danharrin commented on packages/admin/src/Navigation/NavigationItem.php
> +        return $this->isHidden;
```suggestion
        if ($this->evaluate($this->isHidden)) {
            return true;
        }

        return ! $this->evaluate($this->isVisible);
```

2023-05-28 08:11 UTC, danharrin commented on packages/admin/src/Navigation/NavigationItem.php
> +    public function getHidden(): ?bool
```suggestion
    public function getHidden(): bool
```

2023-05-28 08:11 UTC, danharrin commented on packages/admin/src/Navigation/NavigationItem.php
> +    public function getVisible(): ?bool
```suggestion
    public function getVisible(): bool
```

2023-05-28 08:11 UTC, danharrin commented on packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
> +    'hidden' => null,
So these changes should be removed and replaced with changes in the code that returns the navigation structure. Test should also be updated

2023-05-28 08:12 UTC, danharrin commented
Please mark this as `Ready for review` when the refactor is complete as requested :)

2023-05-30 19:19 UTC, ousid commented
Hi, Dan. 

Sure thing, I'll update the PR As soon as I can :)

2023-06-08 07:19 UTC, danharrin requested changes

2023-06-08 07:19 UTC, danharrin commented on packages/admin/resources/views/components/layouts/app/sidebar/group.blade.php
> +                @if ($item->getVisible() || ! $item->getHidden())
```suggestion
                @if ($item->getVisible())
```

2023-06-11 17:02 UTC, merged

2023-06-11 17:02 UTC, danharrin commented
Thanks