UI: Fix display required label in Safari
laravel-filament/filament pull request #6717
Opened 2023-06-07 14:05 UTC by bnzo

For some weirdly reason, when you have a required field label containing an hyphen character, the label is displayed with a carrier return in Safari:

<img width="414" alt="Screenshot 2023-06-07 at 16 02 54" src="https://github.com/filamentphp/filament/assets/17174973/29df55ce-ae21-4ef2-8a81-4e3f6140f621">

This quick fix will prevent this UI behaviour:

<img width="403" alt="Screenshot 2023-06-07 at 16 03 04" src="https://github.com/filamentphp/filament/assets/17174973/35ec5e56-1fbe-485c-b4b7-303764978475">

2023-06-07 14:07 UTC, zepfietje requested changes

2023-06-07 14:07 UTC, zepfietje commented on packages/forms/resources/views/components/field-wrapper/label.blade.php
> +            <span class="whitespace-nowrap">
Could you try removing this wrapping `span` and moving `<sup>` onto the same line as `@if`? I recently noticed the asterisk doesn't stick to the final word anymore.

2023-06-07 14:23 UTC, bnzo commented
I made basic label tests and it seems displayed correctly, without the span, I kept the `whitespace-nowrap` into the `<sup>` tag

2023-06-07 15:01 UTC, zepfietje commented
Could you try if it still works without the `whitespace-nowrap` class? I believe it did when I tested.

Also the indentation needs to be reduced a little.

2023-06-07 18:28 UTC, bnzo commented
It works with `whitespace-nowrap` class attribute indeed. But if the label is the exact size of the input, the required `*` is displayed with a carrier return. This is a rare case but that is why I kept it.

2023-06-07 19:03 UTC, zepfietje commented on packages/forms/resources/views/components/field-wrapper/label.blade.php
> +                 ])
```suggestion
             @class([
                 'text-danger-700 font-medium whitespace-nowrap',
                 'dark:text-danger-400' => config('forms.dark_mode'),
             ])
```

2023-06-07 19:05 UTC, zepfietje commented on packages/forms/resources/views/components/field-wrapper/label.blade.php
> +             ])
```suggestion
                @class([
                    'text-danger-700 font-medium whitespace-nowrap',
                    'dark:text-danger-400' => config('forms.dark_mode'),
                ])
```

2023-06-07 19:06 UTC, zepfietje commented
Ah I see why that class is still required indeed.
Thanks for having a look, @bnzo!

This should be ready for testing/merging, @danharrin.

2023-06-11 16:19 UTC, merged

2023-06-12 16:19 UTC, elmergustavo commented
Good, thanks 💚