Add Option to Persist Section Collapse State
laravel-filament/filament pull request #7392
Opened 2023-08-02 12:00 UTC by DarpanKulkarni

Added an option that allow to persist the sections collapse state to the browser's LocalStorage. This enhancement leverages the Alpine.js Persist plugin, which is now included with Livewire 3.

The sections state can be persisted using `->persistCollapseState()`.

The localStorage keys use the component's id, which is generated using the section heading. If, for some reason, two or more sections have the same headings, the `->id()` can be used to avoid conflicts.

The changes have been throughly tested. However, I have identified one minor issue related to flash of content during the page reload when the section is persisted and expanded. This is because the collapse toggle behaviour is managed by Alpine.js on the client side, and it's not feasible to conditionally add x-cloak.  I think this is minor issue an can be ignored. I will continue investigating potential solutions to address this issue, any suggestions or feedback from the team are welcomed and highly appreciated.

Thank you for your time and consideration.

2023-08-02 12:58 UTC, saade commented on packages/infolists/src/Components/Concerns/CanBeCollapsed.php
> +    protected bool|Closure $isCollapsed = false;
```suggestion
    protected bool | Closure $isCollapsed = false;
```

2023-08-02 12:59 UTC, saade commented on packages/infolists/src/Components/Concerns/CanBeCollapsed.php
> +    protected bool|Closure|null $isCollapsible = null;
```suggestion
    protected bool | Closure | null $isCollapsible = null;
```

2023-08-02 12:59 UTC, saade commented on packages/infolists/src/Components/Concerns/CanBeCollapsed.php
> +    protected bool|Closure|null $shouldPersistCollapseState = null;
```suggestion
    protected bool | Closure | null $shouldPersistCollapseState = null;
```

2023-08-02 12:59 UTC, zepfietje commented
Could you undo the formatting changes by running Pint?

2023-08-02 12:59 UTC, saade commented on packages/infolists/src/Components/Concerns/CanBeCollapsed.php
> +    public function collapsed(bool|Closure $condition = true, bool $shouldMakeComponentCollapsible = true): static
```suggestion
    public function collapsed(bool | Closure $condition = true, bool $shouldMakeComponentCollapsible = true): static
```

2023-08-02 13:00 UTC, saade commented on packages/infolists/src/Components/Concerns/CanBeCollapsed.php
> +        return (bool)$this->evaluate($this->isCollapsed);
```suggestion
        return (bool) $this->evaluate($this->isCollapsed);
```

2023-08-02 13:00 UTC, saade commented on packages/infolists/src/Components/Concerns/CanBeCollapsed.php
> +    public function collapsible(bool|Closure|null $condition = true): static
```suggestion
    public function collapsible(bool | Closure | null $condition = true): static
```

2023-08-02 13:00 UTC, saade commented on packages/infolists/src/Components/Concerns/CanBeCollapsed.php
> +        return (bool)$this->evaluate($this->isCollapsible);
```suggestion
        return (bool) $this->evaluate($this->isCollapsible);
```

2023-08-02 13:00 UTC, saade commented on packages/infolists/src/Components/Concerns/CanBeCollapsed.php
> +    public function persistCollapseState(bool|Closure|null $condition = true): static
```suggestion
    public function persistCollapseState(bool | Closure | null $condition = true): static
```

2023-08-02 13:00 UTC, saade commented on packages/infolists/src/Components/Concerns/CanBeCollapsed.php
> +        return (bool)($this->evaluate($this->shouldPersistCollapseState) ?? false);
```suggestion
        return (bool) ($this->evaluate($this->shouldPersistCollapseState) ?? false);
```

2023-08-09 12:43 UTC, zepfietje requested changes

2023-08-09 12:43 UTC, zepfietje commented on packages/forms/resources/views/components/section.blade.php
> +    :persistCollapseState="$shouldPersistCollapseState()"
Please use kebab case as elsewhere.

2023-09-09 12:56 UTC, danharrin commented
Hi, thanks for the PR. I think it's important to give you a bit of information as to why this PR has been tagged as "low priority". We really appreciate all contributions, and intend to visit this in the future, and hopefully merge it if it is a suitable feature for the framework.

However, reviewing PRs, and often rewriting them on behalf of the author to ensure they are consistent with the rest of the framework, consumes a lot of my time. At the moment we have a large backlog of bug reports that I am prioritising, since most of these affect functionality that worked in a previous version and are now impacting real projects. Hopefully you can see how that work comes first before introducing new features that people aren't using in projects yet.

Again, thank you for contributing and I'm looking forward to reviewing this PR when our backlog of bug reports has reduced.

2023-11-25 21:46 UTC, merged

2023-11-25 21:46 UTC, danharrin commented
Thanks!