Feature/model namespacing
laravel-filament/filament pull request #7559
Opened 2023-08-08 14:04 UTC by JamieCee20

**What has changed?**

Update to the MakeResourceCommand file that will allow the argument of namespace in the scenarios where generating a resource for a model isn't in the App\Models path.

**Usage**

> make:filament-resource {name?} {--namespace=} {--soft-deletes} {--view} {--G|generate} {--S|simple} {--panel=} {--F|force}

Pass the namespace argument to detect the model in that namespace, for example --namespace=My\Custom\Namespace

2023-08-08 19:29 UTC, danharrin commented
I think it should be `--namespace` instead of `--model`

Please remove the `dd()` and other formatting changes that your IDE made

2023-08-08 19:48 UTC, JamieCee20 commented
> I think it should be `--namespace` instead of `--model`
> 
> Please remove the `dd()` and other formatting changes that your IDE made

I shall do that tomorrow for the dd, apologies as well, I have an autoformatter following psr-2, Ill turn it off haha.

Could I just get some clarification on the --namespace not --model as Im sure I set it as --namespace?

2023-08-08 20:05 UTC, danharrin commented
Sorry, I meant it should be `--model` instead of `--namespace`. My fault

2023-08-09 09:06 UTC, JamieCee20 commented
@danharrin I have made the changes to use --model instead of --namespace, as well as changing the stub to prevent always using App\Models before including the model namespace/class.

2023-08-21 08:52 UTC, zepfietje commented on packages/panels/src/Commands/Aliases/MakeResourceCommand.php
> +    protected $signature = 'filament-resource {name?} {--model=} {--soft-deletes} {--view} {--G|generate} {--S|simple} {--panel=} {--F|force}';
Seems like an unintentional breaking change?

```suggestion
    protected $signature = 'filament:resource {name?} {--model=} {--soft-deletes} {--view} {--G|generate} {--S|simple} {--panel=} {--F|force}';
```

2023-09-09 12:51 UTC, danharrin commented
Hi, thanks for the PR. I think it's important to give you a bit of information as to why this PR has been tagged as "low priority". We really appreciate all contributions, and intend to visit this in the future, and hopefully merge it if it is a suitable feature for the framework.

However, reviewing PRs, and often rewriting them on behalf of the author to ensure they are consistent with the rest of the framework, consumes a lot of my time. At the moment we have a large backlog of bug reports that I am prioritising, since most of these affect functionality that worked in a previous version and are now impacting real projects. Hopefully you can see how that work comes first before introducing new features that people aren't using in projects yet.

Again, thank you for contributing and I'm looking forward to reviewing this PR when our backlog of bug reports has reduced.

2023-11-18 14:13 UTC, danharrin requested changes

2023-11-18 14:13 UTC, danharrin commented on packages/panels/src/Commands/MakeResourceCommand.php
> +    protected function getModelFromNamespace($modelName)
```suggestion
    protected function getModelFromNamespace($modelName): string
```

2023-11-18 14:13 UTC, danharrin commented on packages/panels/src/Commands/MakeResourceCommand.php
> +            'model' => $model === 'Resource' ? 'Resource as ResourceModel' : (($this->option('model')) ? $model : "App\Models\\" . $model),
```suggestion
            'model' => $model === 'Resource' ? 'Resource as ResourceModel' : ($this->option('model') ? $model : 'App\Models\\' . $model),
```

2023-11-18 14:13 UTC, danharrin commented on packages/panels/src/Commands/MakeResourceCommand.php
> +        $model = $modelNamespace ? $this->getModelFromNamespace($modelNamespace) : $this->getModelFromNamespace($modelName);
```suggestion
        $model = $this->getModelFromNamespace(filled($modelNamespace) ? $modelNamespace : $modelName);
```

2023-11-18 14:17 UTC, danharrin commented on packages/panels/src/Commands/MakeResourceCommand.php
> +            'model' => $model === 'Resource' ? 'Resource as ResourceModel' : ($this->option('model') ? $model : 'App\Models\\' . $model),
```suggestion
            'model' => ($model === 'Resource') ? 'App\\Models\\Resource as ResourceModel' : ($this->option('model') ? $model : ('App\\Models\\' . $model)),
```

2023-11-18 17:22 UTC, danharrin approved these changes

2023-11-18 17:22 UTC, merged