fix #7092 global search container full width on small device
laravel-filament/filament pull request #7728
Opened 2023-08-13 21:25 UTC by rasasak

Global search containew full width on small displays
(before it hat SM breakpoint)

Before:
![1](https://github.com/filamentphp/filament/assets/28921659/7ee52a5c-08c9-436a-9e2d-1fe9c2a522e0)

After:
![2](https://github.com/filamentphp/filament/assets/28921659/8b7d5aa2-1e2f-4570-add8-c8535d9e38d6)

- [x] Changes have been thoroughly tested to not break existing functionality.
- [nothing to document ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

2023-08-14 09:20 UTC, zepfietje commented
Thanks for this PR, @rasasak.
Could you add margin around the panel so it doesn't stick to the screen edges?

2023-08-14 09:22 UTC, zepfietje requested changes

2023-08-14 09:22 UTC, zepfietje commented on packages/panels/resources/views/components/global-search/results-container.blade.php
> +            'fi-global-search-results-ctn absolute start-0 sm:start-auto sm:end-0 z-10 mt-2 max-h-96 w-full sm:w-screen sm:max-w-sm overflow-auto rounded-lg bg-white shadow-lg ring-1 ring-gray-950/5
Should probably use `inset-x-` (see my other comment).

2023-08-14 11:48 UTC, rasasak commented
@zepfietje  yeah you are right !  
how big inset ?  4 ? - it will be same as widgets etc ... 
but in my opinion  inset-x-3 have nice 3d efect .. because is little bit bigger, because is little closer to user 

inset-x-4:
![4](https://github.com/filamentphp/filament/assets/28921659/974a112c-bf9e-4220-9ace-cb8dd1b9e368)

inset-x-3:
![3](https://github.com/filamentphp/filament/assets/28921659/923f2c4d-5b44-42f5-adb9-7b74456762fa)

2023-08-15 08:55 UTC, zepfietje commented
Thanks, @rasasak!

2023-08-15 09:01 UTC, merged