Update 13-upgrade-guide.md : generating JS & CSS missing instruction
laravel-filament/filament pull request #8069
Opened 2023-08-25 11:58 UTC by Sicklou

Hello,

It was impossible for me to use the automatic update.

After making the changes described in the migration guide, I encounterd issues because the JS & CSS files was not published in the public folder.

Executing `filament:install --tables` solved it.

2023-08-29 19:03 UTC, danharrin commented
Note to future self: check number of upgrade guide page for all packages and add `filament:assets`

2023-08-30 13:33 UTC, ziming requested changes

2023-08-30 13:33 UTC, ziming commented on packages/tables/docs/13-upgrade-guide.md
> +After upgrading to v3, you need to execute `php artisan install --tables` in order to generate JavaScript and CSS files.
When I try this command I got:

>    ERROR  Command "install" is not defined. Did you mean one of these?  

So what I think you want is

```suggestion
After upgrading to v3, you need to execute `php artisan filament:install --tables` in order to generate JavaScript and CSS files.
```

2023-08-30 13:59 UTC, Sicklou commented
@ziming you are right ! Thank you !

2023-08-31 10:21 UTC, merged