Provide a configuration property to determine if remove uploaded file button is shown
laravel-filament/filament pull request #8167
Opened 2023-08-30 02:31 UTC by lucasdotvin

The idea here is simply to provide a way to hide the uploaded file button in Filepond through their constructor option `allowRemove`.

Developers that wish their file component does not show a remove button (in cases where it is not allowed to change the file, for instance) can call `removable(false)` to do so.

- [ ] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

2023-08-31 09:05 UTC, danharrin requested changes
Not sure if this should be isRemovable, we use isDeletable everywhere else

2023-08-31 09:05 UTC, danharrin commented on packages/forms/resources/views/components/file-upload.blade.php
> +                    allowRemove: @js($isRemovable()),
Please pass this in as isRemovable and map to allowRemove in the JS file

2023-08-31 21:18 UTC, lucasdotvin commented
Well pointed! I'll rename the property and map it in the JS file.

2023-09-01 05:30 UTC, merged

2023-09-01 05:30 UTC, danharrin commented
Thanks