Throw exception when creating Filament user without panel
laravel-filament/filament pull request #8823
Opened 2023-10-02 10:00 UTC by stfnxd

- [ Yes ] Changes have been thoroughly tested to not break existing functionality.
- [ No ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ No ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

2023-10-03 08:54 UTC, zepfietje commented on packages/panels/src/Commands/MakeUserCommand.php
```suggestion
```

2023-10-03 08:54 UTC, zepfietje commented on packages/panels/src/Commands/MakeUserCommand.php
> +
```suggestion
```

2023-10-03 08:54 UTC, zepfietje commented on packages/panels/src/Commands/MakeUserCommand.php
> +
```suggestion
```

2023-10-03 12:37 UTC, danharrin commented
Instead of catching all exceptions, why not do a pre-emptive check before and see if the panel exists? Catching all exceptions does not sound like it will give an accurate solution in many cases.

2023-10-09 08:23 UTC, stfnxd commented
Code should now be optimal, and pre-emptive check if the panel exist.

Unsure if you prefere ! or === null, so made ===null.

2023-10-09 09:27 UTC, zepfietje requested changes
Please undo all formatting changes and empty lines that were added/removed.

2023-10-09 09:42 UTC, zepfietje commented
There's still a couple more, @stfnxd.
Please check the diff.

2023-10-09 10:07 UTC, stfnxd commented
Is this what you mean? @zepfietje 

If not, i am unsure what you are looking for, any chance you can link me some documentation on the formatting?

2023-10-09 10:20 UTC, merged

2023-10-09 10:20 UTC, danharrin commented
Thanks