improved sticky form actions behavior
laravel-filament/filament pull request #9948
Opened 2023-11-29 12:03 UTC by drhoussem

- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

In the actual code the sticky form actions are not always showing when scrolling, it only works staring for a certain page length, I used a repeater in the video to show you that.

https://github.com/filamentphp/filament/assets/993307/4c4b9765-8070-48c7-86c1-7f65f3f51b25

I changed the code a little bit to make the sticky form actions beavior more consistent

https://github.com/filamentphp/filament/assets/993307/14aa6824-5d91-448f-b0cd-3e63b0be7afd

2023-11-29 12:08 UTC, danharrin commented on packages/panels/resources/views/components/form/actions.blade.php
> +                evaluatePageScrollPosition() {
```suggestion
                evaluatePageScrollPosition: function () {
```

2023-11-29 12:15 UTC, zepfietje commented on packages/panels/resources/views/components/form/actions.blade.php
> +
```suggestion

```

2023-11-29 12:15 UTC, zepfietje commented on packages/panels/resources/views/components/form/actions.blade.php
> +
```suggestion
```

2023-11-29 12:15 UTC, zepfietje commented on packages/panels/resources/views/components/form/actions.blade.php
> +
```suggestion
```

2023-11-29 12:16 UTC, zepfietje commented on packages/panels/resources/views/components/form/actions.blade.php
>                  isSticky: false,
```suggestion
                isSticky: false,

```

2023-11-29 12:18 UTC, zepfietje requested changes
From your video it seems like this PR breaks the removal of the floating box when the actions are in their original non-sticky position. Also, while we're at it, could you make sure the actions show on page load already when they need to?

2023-11-29 23:11 UTC, drhoussem commented
@zepfietje I made the necessary changes.

2023-11-30 10:35 UTC, zepfietje commented
Thanks, @drhoussem.
Could you post a screen recording of the new behavior?

2023-11-30 11:34 UTC, drhoussem commented
Here it is

https://github.com/filamentphp/filament/assets/993307/7ca208a1-11ca-45c5-a4b4-62de0690d703

2023-11-30 11:46 UTC, zepfietje commented
Hmm, still doesn't seem like the sticky box disappears at the right point?

2023-11-30 12:11 UTC, drhoussem commented
What do you think now. By the way, I found is no easy way to determine if the actions are in their original non-sticky position.

https://github.com/filamentphp/filament/assets/993307/79ad0790-39a8-45ca-8245-c11d0794dd71

2023-11-30 12:58 UTC, danharrin commented
I don't think there should be a jump, but as soon as the box lines up with the actions it should not have a background

2023-11-30 17:31 UTC, zepfietje commented
Exactly as @danharrin said.

Please do some searching on Google, @drhoussem.
I had a quick look, and it should be possible (in a little hackish way) to determine if the sticky element is currently stuck or not.

2023-12-01 11:55 UTC, drhoussem commented
The new behavior

https://github.com/filamentphp/filament/assets/993307/e41b7a43-2fff-4906-b6b3-6d84f1fceaad

I had to change they way I approach this, this time I had to stick the element to bottom and used x-intersect (first time I use it) to detect when the element comes to view port.

I also made the sticky actions bar take full screen width on mobile devices.

2023-12-01 13:20 UTC, zepfietje commented
Thanks for working on this, @drhoussem.
What happened to the actions bar width when stuck? 😅

2023-12-01 13:56 UTC, drhoussem commented
@zepfietje I don't understand what do you mean?

2023-12-01 14:06 UTC, zepfietje commented
Sorry, it seemed like the width was wrong, but it only seemed like that because of the right section.

2023-12-04 00:20 UTC, zepfietje requested changes

2023-12-04 00:20 UTC, zepfietje commented on packages/panels/resources/views/components/form/actions.blade.php
> +            }"
Could you move this after `x-bind:class` and run Prettier to fix formatting issues, @drhoussem?

2023-12-04 08:12 UTC, drhoussem commented on packages/panels/resources/views/components/form/actions.blade.php
> +            }"
done

2023-12-04 11:27 UTC, zepfietje commented
Having issues checking out to this PR locally, so I'll merge it and clean it up on 3.x.
Thanks, @drhoussem.

2023-12-04 11:27 UTC, merged

2023-12-04 12:13 UTC, zepfietje commented
@drhoussem, I've had to revert all changes, as the behavior was more broken now than before and it takes a lot of work to get it right.

Feel free to make another attempt, while:

- Keeping the current design
- Running Prettier before requesting a review
- Make sure to thoroughly test all cases

2023-12-04 12:17 UTC, drhoussem commented
@zepfietje could you tell me what was broken on your side? You should run filament upgrade to make sure that the new changes are reflected.

2023-12-04 12:59 UTC, zepfietje commented
While refactoring I couldn't get it to work reliably anymore.
If you believe it's just the design changes that need to be updated, please create a new PR where you handle that. Then I can do another review.